# Generated by Django 3.1.5 on 2021-01-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('block_type', models.CharField(choices=[('standard', 'Standard'), ('social', 'Social'), ('wide', 'Wide')], default='standard', max_length=32)),
                ('link_url', models.CharField(blank=True, help_text='An external URL (https://...) or an internal URL (/interactives/2019annualreport/).', max_length=512)),
                ('image_promotion', models.ForeignKey(blank=True, help_text='The background image of the promotion block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Promotion Image')),
                ('image_promotion_small', models.ForeignKey(blank=True, help_text='The background image of the promotion block. Only used for wide promotion blocks as a replacement when screen width is small. Ex. Multimedia landing page wide promotion block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Promotion Image (Small)')),
            ],
            options={
                'verbose_name': 'Promotion Block',
            },
        ),
    ]
