# Generated by Django 3.1.5 on 2021-01-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBlockListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Promotion List Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PromotionBlockPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('block_type', models.CharField(choices=[('normal', 'Normal'), ('social', 'Social'), ('wide', 'wide')], default='normal', max_length=32)),
                ('link_url', models.CharField(blank=True, help_text='An external URL (https://...) or an internal URL (/interactives/2019annualreport/).', max_length=512)),
                ('image_promotion', models.ForeignKey(blank=True, help_text='The background image of the promotion block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Promotion Image')),
                ('image_promotion_small', models.ForeignKey(blank=True, help_text='The background image of the promotion block. Only used for wide promotion blocks as a replacement when screen width is small. Ex. Multimedia landing page wide promotion block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Promotion Image (Small)')),
            ],
            options={
                'verbose_name': 'Promotion Block',
            },
            bases=('wagtailcore.page',),
        ),
    ]
