# Generated by Django 5.2 on 2026-03-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20211122_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionblock',
            name='accessible_name',
            field=models.CharField(blank=True, help_text='Describe the visual content of this block for screen readers (e.g. "Register for the 2025 Annual Conference"). Used as the aria-label.', max_length=255, verbose_name='Accessible Name'),
        ),
    ]
