# Generated by Django 5.0.6 on 2025-05-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_cigionlinerendition_file'),
        ('portal', '0002_portalhomepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalhomepage',
            name='image_banner',
            field=models.ForeignKey(blank=True, help_text='A banner image to be displayed as background of the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='image_banner',
            field=models.ForeignKey(blank=True, help_text='A banner image to be displayed as background of the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image'),
        ),
    ]
