# Generated by Django 3.0.7 on 2020-06-26 18:42

from django.db import migrations, models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_topicpage_drupal_taxonomy_id'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='embed_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='related_files',
            field=wagtail.core.fields.StreamField([('file', wagtail.documents.blocks.DocumentChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='speakers',
            field=wagtail.core.fields.StreamField([('speaker', wagtail.core.blocks.PageChooserBlock(page_type=['people.PersonPage'], required=True)), ('external_speaker', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='research.TopicPage'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='twitter_hashtag',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
