# Generated by Django 3.1.1 on 2020-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('events', '0002_eventpage_multimedia_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('cigi_sponsored', 'CIGI Sponsored'), ('cinema_series', 'Cinema Series'), ('community_event', 'Community Event'), ('conference', 'Conference'), ('global_policy_forum', 'Global Policy Forum'), ('noon_lecture_series', 'Noon Lecture Series'), ('panel_discussion', 'Panel Discussion'), ('publication_launch', 'Publication Launch'), ('roundtable', 'Roundtable'), ('seminar', 'Seminar'), ('signature_lecture', 'Signature Lecture'), ('virtual_event', 'Virtual Event'), ('workshop', 'Workshop')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='multimedia_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Multimedia'),
        ),
    ]
