# Generated by Django 3.1.6 on 2021-02-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_hero_stream_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='projects',
        ),
    ]
