# Generated by Django 3.1.7 on 2021-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_update_table_stream_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
