# Generated by Django 3.1.7 on 2021-04-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_use_custom_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
