# Generated by Django 3.2.4 on 2021-12-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventpage_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('cigi_sponsored', 'CIGI Sponsored'), ('cinema_series', 'Cinema Series'), ('community_event', 'Community Event'), ('conference', 'Conference'), ('global_policy_forum', 'Global Policy Forum'), ('noon_lecture_series', 'Noon Lecture Series'), ('panel_discussion', 'Panel Discussion'), ('publication_launch', 'Publication Launch'), ('roundtable', 'Round Table'), ('seminar', 'Seminar'), ('signature_lecture', 'Signature Lecture'), ('virtual_event', 'Virtual Event'), ('workshop', 'Workshop')], max_length=32, null=True),
        ),
    ]
