# Generated by Django 3.2.4 on 2021-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventpage_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
    ]
