# Generated by Django 3.2.4 on 2022-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_feature_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
