# Generated by Django 3.2.15 on 2022-10-18 14:50

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_eventlistpage_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
