# Generated by Django 3.2.15 on 2022-11-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_eventpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='event_format',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('virtual', 'Virtual'), ('in-person', 'In Person')], max_length=32, null=True),
        ),
    ]
