# Generated by Django 4.0 on 2023-03-06 18:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20221214_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlistpage',
            name='featured_events',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['events.EventPage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_vertical', 'Medium Vertical'), ('large', 'Large')]))]))], blank=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='EventListPageFeaturedEvent',
        ),
    ]
