# Generated by Django 4.0 on 2023-03-27 03:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_eventlistpage_featured_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlistpage',
            name='featured_events',
            field=wagtail.fields.StreamField([('event', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['events.EventPage'], required=True))]))], blank=True, use_json_field=True),
        ),
    ]
