# Generated by Django 4.0 on 2023-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_eventlistpage_featured_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='livestream_url',
            field=models.URLField(blank=True, help_text='The Vimeo URL of the livestream event.', verbose_name='Livestream URL'),
        ),
    ]
