# Generated by Django 3.2.18 on 2024-06-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20240619_1412'),
        ('events', '0026_auto_20240619_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme'),
        ),
    ]
