# Generated by Django 5.0.6 on 2025-05-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventpage_event_agenda_eventpage_registration_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='email_recipient',
            field=models.EmailField(blank=True, help_text='Email address to send notifications to when a file is uploaded via submission form.', max_length=254, null=True),
        ),
    ]
