# Generated by Django 5.0.6 on 2025-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_eventpage_event_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='registration_text',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
