# Generated by Django 5.0.6 on 2025-05-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_eventpage_email_recipient'),
        ('events', '0031_alter_eventlistpage_body_alter_eventpage_body'),
    ]

    operations = [
    ]
