# Generated by Django 5.0.6 on 2025-11-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_alter_eventlistpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_access',
            field=models.IntegerField(blank=True, choices=[(0, 'Private'), (1, 'Public')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_format',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('virtual', 'Virtual'), ('in-person', 'In Person')], max_length=32, null=True),
        ),
    ]
