# Generated by Django 5.0.6 on 2025-11-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_eventpage_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='website_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
