# Generated by Django 5.0.6 on 2026-02-19 13:25

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_alter_eventpage_website_url'),
        ('images', '0005_cigionlineimage_description'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('button', 6), ('image', 13), ('divider', 14), ('answers', 15), ('attachment_hint', 17)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {'icon': 'title', 'label': 'Heading'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 64, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 5)]], {'icon': 'link', 'label': 'Button'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': "Use if you can't choose an image.", 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 11: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'In pixels (e.g., 560).', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 7), ('image_url', 8), ('alt', 9), ('alignment', 10), ('max_width', 11), ('link', 12)]], {'icon': 'image', 'label': 'Image'}), 14: ('wagtail.blocks.static_block.StaticBlock', (), {'icon': 'horizontalrule', 'label': 'Divider'}), 15: ('wagtail.blocks.static_block.StaticBlock', (), {'icon': 'list-ul', 'label': 'Registrant Answers'}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('note', 16)]], {'icon': 'paperclip', 'label': 'Attachment Hint (non‑rendered)'})})),
            ],
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventRegistrationReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Event registration report',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='RegistrationFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='is_private_registration',
            field=models.BooleanField(default=False, help_text='Require invite token or private link to register.'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='registration_image_banner',
            field=models.ForeignKey(blank=True, help_text='A banner image to be displayed as background of the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('include_statuses', models.TextField(blank=True, default='', help_text='Comma-separated registrant statuses (e.g. "confirmed,waitlisted"). Leave blank for all.')),
                ('include_type_slugs', models.TextField(blank=True, default='', help_text='Comma-separated registration type slugs (e.g. "general,student"). Leave blank for all.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtaildocs.document')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='events.eventpage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.emailtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='eventpage',
            name='confirmation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='reminder_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='waitlist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_type_slugs', models.TextField(blank=True, help_text='Example: vip,speaker')),
                ('token', models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.eventpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('uploaded_document_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('manage_token_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='events.eventpage')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrants', to='events.invite')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='events.emailcampaign')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='events.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('field_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_allowed_types', models.CharField(blank=True, help_text='Allowed extensions (comma-separated), e.g. pdf,docx,png', max_length=255)),
                ('file_max_mb', models.PositiveIntegerField(blank=True, help_text='Max file size (MB). Leave blank for no limit.', null=True)),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'File upload'), ('conditional_text', 'Conditional text (checkbox + details)'), ('conditional_dropdown_other', 'Conditional dropdown (Other + textbox)')], default='singleline', max_length=32)),
                ('visible_rule', models.CharField(choices=[('all', 'All types'), ('only', 'Only these types'), ('except', 'All except these types')], default='all', max_length=10)),
                ('visible_type_slugs', models.TextField(blank=True, help_text='Comma-separated type slugs (e.g., vip,speaker)')),
                ('required_rule', models.CharField(choices=[('all', 'All types'), ('only', 'Only these types'), ('except', 'All except these types')], default='all', max_length=10)),
                ('required_type_slugs', models.TextField(blank=True, help_text='Comma-separated type slugs')),
                ('conditional_label', models.CharField(blank=True, help_text="Label shown for the checkbox. If blank, uses the field's main label.", max_length=255)),
                ('conditional_details_label', models.CharField(blank=True, help_text='Label for the details textbox (shown only when checked).', max_length=255)),
                ('conditional_details_help_text', models.TextField(blank=True, help_text='Help text shown under the details textbox.')),
                ('conditional_details_required', models.BooleanField(default=True, help_text='Require details textbox when checkbox is checked.')),
                ('conditional_other_value', models.CharField(blank=True, help_text='Which dropdown value triggers the textbox (default: "Other").', max_length=120)),
                ('conditional_other_label', models.CharField(blank=True, help_text="Label for the textbox shown when 'Other' is selected.", max_length=255)),
                ('conditional_other_help_text', models.TextField(blank=True, help_text="Help text for the 'Other' textbox.")),
                ('conditional_other_required', models.BooleanField(default=True, help_text="Require textbox when 'Other' is selected.")),
                ('exclude_from_guest_forms', models.BooleanField(default=False, help_text='Exclude this question from guest attendee forms when using multi-registrations (primary + guests).')),
                ('template', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.registrationformtemplate')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventpage',
            name='registration_form_template',
            field=models.ForeignKey(blank=True, help_text='Choose a reusable set of registration fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.registrationformtemplate'),
        ),
        migrations.CreateModel(
            name='RegistrationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=254)),
                ('manage_token_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_groups', to='events.eventpage')),
            ],
        ),
        migrations.AddField(
            model_name='registrant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrants', to='events.registrationgroup'),
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('custom_confirmation_text', wagtail.fields.RichTextField(blank=True)),
                ('allow_group_registrations', models.BooleanField(default=False, help_text='Allow one email to register multiple attendees (guests) for this registration type.')),
                ('max_guest_registrations', models.PositiveIntegerField(default=5, help_text='Maximum number of additional guests allowed for this registration type (default: 5).')),
                ('confirmation_template_override', models.ForeignKey(blank=True, help_text='Overrides the event confirmation template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_types', to='events.eventpage')),
                ('reminder_template_override', models.ForeignKey(blank=True, help_text='Overrides the event reminder template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate')),
                ('waitlist_template_override', models.ForeignKey(blank=True, help_text='Overrides the event waitlist template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='registrationgroup',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_groups', to='events.registrationtype'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrants', to='events.registrationtype'),
        ),
        migrations.AddConstraint(
            model_name='emailcampaignsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'registrant'), name='uniq_events_emailcampaignsend_campaign_registrant'),
        ),
    ]
