# Generated by Django 5.0.6 on 2025-08-21 19:10

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_emailtemplate_eventpage_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformfield',
            name='required_for_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='events.registrationtype'),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='show_for_types',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='events.registrationtype'),
        ),
    ]
