# Generated by Django 5.0.6 on 2026-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_emailtemplate_eventregistrationreportpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(blank=True, choices=[('cigi_sponsored', 'CIGI Sponsored'), ('cinema_series', 'Cinema Series'), ('community_event', 'Community Event'), ('conference', 'Conference'), ('global_policy_forum', 'Global Policy Forum'), ('internal_event', 'Internal Event'), ('noon_lecture_series', 'Noon Lecture Series'), ('panel_discussion', 'Panel Discussion'), ('publication_launch', 'Publication Launch'), ('roundtable', 'Round Table'), ('seminar', 'Seminar'), ('signature_lecture', 'Signature Lecture'), ('virtual_event', 'Virtual Event'), ('workshop', 'Workshop')], max_length=32, null=True),
        ),
    ]
