# Generated by Django 5.0.6 on 2025-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_alter_registrationformfield_required_for_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='is_private_registration',
            field=models.BooleanField(default=False, help_text='Require invite token or private link to register.'),
        ),
    ]
