# Generated by Django 5.2 on 2026-04-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_eventlistpage_body_alter_eventpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='registration_report_password_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
