# Generated by Django 5.0.6 on 2026-01-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_eventpage_is_private_registration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registrant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registrationformfield',
            name='required_for_types',
        ),
        migrations.RemoveField(
            model_name='registrationformfield',
            name='show_for_types',
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='required_rule',
            field=models.CharField(choices=[('all', 'All types'), ('only', 'Only these types'), ('except', 'All except these types')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='required_type_slugs',
            field=models.TextField(blank=True, help_text='Comma-separated type slugs'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='visible_rule',
            field=models.CharField(choices=[('all', 'All types'), ('only', 'Only these types'), ('except', 'All except these types')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='visible_type_slugs',
            field=models.TextField(blank=True, help_text='Comma-separated type slugs (e.g., vip,speaker)'),
        ),
        migrations.AlterField(
            model_name='registrationtype',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
