# Generated by Django 5.2 on 2026-04-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_eventpage_registration_report_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='test_recipient_emails',
            field=models.TextField(blank=True, default='', help_text='Comma-, semicolon-, or newline-separated email addresses for test sends. These addresses are never included in scheduled campaign sends.'),
        ),
    ]
