# Generated by Django 5.0.6 on 2026-01-07 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_alter_registrant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='allowed_types',
        ),
        migrations.AddField(
            model_name='invite',
            name='allowed_rule',
            field=models.CharField(choices=[('all', 'All public types'), ('only', 'Only these types')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='invite',
            name='allowed_type_slugs',
            field=models.TextField(blank=True, help_text='Comma-separated slugs (e.g., vip)'),
        ),
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrants', to='events.invite'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='registration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrants', to='events.registrationtype'),
        ),
    ]
