# Generated by Django 5.0.6 on 2026-01-07 22:44

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_remove_invite_allowed_types_invite_allowed_rule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='invite',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='allowed_type_slugs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='event',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='events.eventpage'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
