# Generated by Django 5.2 on 2026-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_registrationformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='close_date',
            field=models.DateTimeField(blank=True, help_text='After this date and time, this registration type is hidden and no longer accepts new registrations. Leave blank to keep it open while event registration is open.', null=True),
        ),
    ]
