# Generated by Django 5.0.6 on 2026-01-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_alter_invite_options_invite_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='file_allowed_types',
            field=models.CharField(blank=True, help_text='Allowed extensions (comma-separated), e.g. pdf,docx,png', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='file_max_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Max file size (MB). Leave blank for no limit.', null=True),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'File upload')], default='singleline', max_length=16),
        ),
        migrations.CreateModel(
            name='RegistrantUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_uploads/%Y/%m/%d')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.registrationformfield')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='events.registrant')),
            ],
        ),
    ]
