# Generated by Django 5.0.6 on 2026-01-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_registrationformfield_file_allowed_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='max_capacity',
        ),
    ]
