# Generated by Django 5.2 on 2026-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_registrationtype_close_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'File upload'), ('conditional_text', 'Conditional text (checkbox + details)'), ('conditional_dropdown_other', 'Conditional dropdown (Other + textbox)'), ('conditional_multiselect_other', 'Conditional multiselect (Other + textbox)'), ('mailchimp_optin', 'Opt-in mailing list (Yes/No)')], default='singleline', max_length=32),
        ),
    ]
