# Generated by Django 5.2 on 2026-05-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_alter_registrationformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='mailchimp_tag',
            field=models.CharField(blank=True, help_text='Mailchimp tag to apply to subscribers who opt in via the registration form.', max_length=128),
        ),
    ]
