# Generated by Django 5.0.6 on 2026-01-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_remove_eventpage_max_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='allowed_rule',
            field=models.CharField(choices=[('all', 'All'), ('only', 'Only these'), ('except', 'All except these')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='invite',
            name='allowed_type_slugs',
            field=models.TextField(blank=True, help_text='Example: vip,speaker'),
        ),
    ]
