# Generated by Django 5.2 on 2026-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_add_eventpage_mailchimp_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='mailchimp_tag',
            field=models.CharField(blank=True, help_text='Mailchimp tag(s) to apply to subscribers who opt in via the registration form. Separate multiple tags with commas.', max_length=255),
        ),
    ]
