# Generated by Django 5.0.6 on 2026-01-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_alter_invite_allowed_rule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='allowed_rule',
            field=models.CharField(choices=[('all', 'All'), ('only', 'Only these')], default='all', max_length=10),
        ),
    ]
