# Generated by Django 5.0.6 on 2026-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_alter_invite_allowed_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrantUpload',
        ),
    ]
