# Generated by Django 5.0.6 on 2026-01-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_delete_registrantupload'),
        ('images', '0005_cigionlineimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='registration_image_banner',
            field=models.ForeignKey(blank=True, help_text='A banner image to be displayed as background of the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image'),
        ),
    ]
