# Generated by Django 5.0.6 on 2026-01-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_eventpage_registration_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_details_help_text',
            field=models.TextField(blank=True, help_text='Help text shown under the details textbox.'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_details_label',
            field=models.CharField(blank=True, help_text='Label for the details textbox (shown only when checked).', max_length=255),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_details_required',
            field=models.BooleanField(default=True, help_text='Require details textbox when checkbox is checked.'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_label',
            field=models.CharField(blank=True, help_text="Label shown for the checkbox. If blank, uses the field's main label.", max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'File upload'), ('conditional_text', 'Conditional text (checkbox + details)')], default='singleline', max_length=16),
        ),
    ]
