# Generated by Django 5.0.6 on 2026-01-21 19:42

import django.db.models.deletion
import modelcluster.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_registrationformfield_conditional_details_help_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationFormTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='registrationformfield',
            name='event',
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='field_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='registration_form_template',
            field=models.ForeignKey(blank=True, help_text='Choose a reusable set of registration fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.registrationformtemplate'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='template',
            field=modelcluster.fields.ParentalKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.registrationformtemplate'),
            preserve_default=False,
        ),
    ]
