# Generated by Django 5.2 on 2026-09-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_eventpage_add_to_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_parent',
            field=models.ForeignKey(blank=True, help_text='Show this field only when the selected question has one of the values below.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_children', to='events.registrationformfield'),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_parent_values',
            field=models.TextField(blank=True, help_text='Trigger values, one per line. Example: Yes'),
        ),
    ]
