# Generated by Django 5.0.6 on 2026-01-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_registrationformtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_other_help_text',
            field=models.TextField(blank=True, help_text="Help text for the 'Other' textbox."),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_other_label',
            field=models.CharField(blank=True, help_text="Label for the textbox shown when 'Other' is selected.", max_length=255),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_other_required',
            field=models.BooleanField(default=True, help_text="Require textbox when 'Other' is selected."),
        ),
        migrations.AddField(
            model_name='registrationformfield',
            name='conditional_other_value',
            field=models.CharField(blank=True, help_text='Which dropdown value triggers the textbox (default: "Other").', max_length=120),
        ),
        migrations.AlterField(
            model_name='registrationformfield',
            name='field_type',
            field=models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field'), ('file', 'File upload'), ('conditional_text', 'Conditional text (checkbox + details)'), ('conditional_dropdown_other', 'Conditional dropdown (Other + textbox)')], default='singleline', max_length=32),
        ),
    ]
