# Generated by Django 5.0.6 on 2026-01-23 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_registrationformfield_conditional_other_help_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='waitlist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
    ]
