# Generated by Django 5.0.6 on 2026-01-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_eventpage_waitlist_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='name',
            new_name='title',
        ),
    ]
