# Generated by Django 5.0.6 on 2026-01-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_rename_name_emailtemplate_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='merge_vars_help',
        ),
    ]
