# Generated by Django 5.0.6 on 2026-01-28 17:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_remove_emailtemplate_merge_vars_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('button', 6), ('image', 13), ('divider', 14), ('attachment_hint', 16)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'H1'), ('h2', 'H2'), ('h3', 'H3')]}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {'icon': 'title', 'label': 'Heading'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ul', 'ol']}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 64, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('url', 5)]], {'icon': 'link', 'label': 'Button'}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': "Use if you can't choose an image.", 'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')]}), 11: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'In pixels (e.g., 560).', 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('image', 7), ('image_url', 8), ('alt', 9), ('alignment', 10), ('max_width', 11), ('link', 12)]], {'icon': 'image', 'label': 'Image'}), 14: ('wagtail.blocks.static_block.StaticBlock', (), {'icon': 'horizontalrule', 'label': 'Divider'}), 15: ('wagtail.blocks.TextBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('note', 15)]], {'icon': 'paperclip', 'label': 'Attachment Hint (non‑rendered)'})}),
        ),
    ]
