# Generated by Django 5.0.6 on 2026-01-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='manage_token_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64),
        ),
    ]
