# Generated by Django 5.0.6 on 2026-01-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_registrant_manage_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailCampaignSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='events.emailcampaign')),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='events.registrant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='emailcampaignsend',
            constraint=models.UniqueConstraint(fields=('campaign', 'registrant'), name='uniq_events_emailcampaignsend_campaign_registrant'),
        ),
    ]
