# Generated by Django 5.0.6 on 2026-01-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0066_emailcampaign_completed_at_emailcampaign_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcampaign',
            old_name='include_type_ids',
            new_name='include_type_slugs',
        ),
    ]
