# Generated by Django 5.0.6 on 2026-01-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0067_rename_include_type_ids_emailcampaign_include_type_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='include_statuses',
            field=models.TextField(blank=True, default='', help_text='Comma-separated registrant statuses (e.g. "confirmed,waitlisted"). Leave blank for all.'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='include_type_slugs',
            field=models.TextField(blank=True, default='', help_text='Comma-separated registration type slugs (e.g. "general,student"). Leave blank for all.'),
        ),
    ]
