# Generated by Django 5.0.6 on 2026-02-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_alter_emailtemplate_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='confirmation_template_override',
            field=models.ForeignKey(blank=True, help_text='Overrides the event confirmation template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='reminder_template_override',
            field=models.ForeignKey(blank=True, help_text='Overrides the event reminder template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='waitlist_template_override',
            field=models.ForeignKey(blank=True, help_text='Overrides the event waitlist template for this registration type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.emailtemplate'),
        ),
    ]
