# Generated by Django 5.0.6 on 2026-02-06 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_registrationtype_confirmation_template_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='allow_guest_registrations',
            field=models.BooleanField(default=False, help_text='Allow one email to register multiple attendees (guests).'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='max_guest_registrations',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of additional guests allowed per registration (default: 5).'),
        ),
        migrations.CreateModel(
            name='RegistrationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_email', models.EmailField(max_length=254)),
                ('manage_token_hash', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_groups', to='events.eventpage')),
                ('registration_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration_groups', to='events.registrationtype')),
            ],
        ),
        migrations.AddField(
            model_name='registrant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrants', to='events.registrationgroup'),
        ),
    ]
