# Generated by Django 5.0.6 on 2026-02-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_eventpage_allow_guest_registrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='allowed_rule',
            field=models.CharField(choices=[('all', 'All'), ('only', 'Only these')], max_length=10),
        ),
    ]
