# Generated by Django 5.0.6 on 2026-02-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_alter_invite_allowed_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='allow_guest_registrations',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='max_guest_registrations',
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='allow_group_registrations',
            field=models.BooleanField(default=False, help_text='Allow one email to register multiple attendees (guests) for this registration type.'),
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='max_guest_registrations',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of additional guests allowed for this registration type (default: 5).'),
        ),
    ]
