# Generated by Django 5.0.6 on 2026-02-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_remove_eventpage_allow_guest_registrations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='allowed_rule',
        ),
    ]
