# Generated by Django 5.0.6 on 2026-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_emailtemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformfield',
            name='exclude_from_guest_forms',
            field=models.BooleanField(default=False, help_text='Exclude this question from guest attendee forms when using multi-registrations (primary + guests).'),
        ),
    ]
