version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - johnbxu
  ignore:
  - dependency-name: boto3
    versions:
    - 1.16.62
    - 1.17.0
    - 1.17.1
    - 1.17.11
    - 1.17.13
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.32
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.38
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.59
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: botocore
    versions:
    - 1.19.62
    - 1.20.0
    - 1.20.1
    - 1.20.11
    - 1.20.13
    - 1.20.14
    - 1.20.15
    - 1.20.16
    - 1.20.18
    - 1.20.19
    - 1.20.2
    - 1.20.20
    - 1.20.21
    - 1.20.22
    - 1.20.23
    - 1.20.24
    - 1.20.25
    - 1.20.26
    - 1.20.28
    - 1.20.29
    - 1.20.3
    - 1.20.30
    - 1.20.32
    - 1.20.33
    - 1.20.34
    - 1.20.35
    - 1.20.36
    - 1.20.38
    - 1.20.39
    - 1.20.4
    - 1.20.40
    - 1.20.41
    - 1.20.43
    - 1.20.44
    - 1.20.45
    - 1.20.46
    - 1.20.47
    - 1.20.48
    - 1.20.49
    - 1.20.5
    - 1.20.50
    - 1.20.51
    - 1.20.52
    - 1.20.53
    - 1.20.54
    - 1.20.55
    - 1.20.56
    - 1.20.57
    - 1.20.58
    - 1.20.59
    - 1.20.6
    - 1.20.7
    - 1.20.8
    - 1.20.9
  - dependency-name: astroid
    versions:
    - 2.12.12
  - dependency-name: s3transfer
    versions:
    - 0.3.7
    - 0.4.0
    - 0.4.1
  - dependency-name: mailchimp-marketing
    versions:
    - 3.0.37
    - 3.0.38
    - 3.0.40
  - dependency-name: draftjs-exporter
    versions:
    - 4.1.2
  - dependency-name: asgiref
    versions:
    - 3.3.2
    - 3.3.3
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: pycodestyle
    versions:
    - 2.7.0
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: django-treebeard
    versions:
    - "4.5"
    - 4.5.1
  - dependency-name: wagtail
    versions:
    - 2.12.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.22.0
    - 5.24.0
    - 5.24.1
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.2.1
    - 5.2.4
  - dependency-name: swiper
    versions:
    - 6.4.12
    - 6.4.14
    - 6.4.9
    - 6.5.5
    - 6.5.6
    - 6.5.7
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.5
    - 8.2.7
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.15
  - dependency-name: cssnano
    versions:
    - 4.1.11
    - 5.0.0
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: postcss-loader
    versions:
    - 5.1.0
  - dependency-name: scrollreveal
    versions:
    - 4.0.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.8
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.7
  - dependency-name: sass-loader
    versions:
    - 11.0.0
  registries:
  - npm-registry-npm-fontawesome-com
