# Generated by Django 3.1.1 on 2020-10-30 20:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlepage_article_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='series_items',
            field=wagtail.core.fields.StreamField([('series_item', wagtail.core.blocks.PageChooserBlock(page_type=['articles.ArticlePage', 'multimedia.MultimediaPage'], required=True)), ('category_title', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
