# Generated by Django 3.1.5 on 2021-01-19 23:36

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210118_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='cigi_people_mentioned',
            field=wagtail.core.fields.StreamField([('cigi_person', streams.blocks.PersonBlock(page_type=['people.PersonPage'], required=True))], blank=True),
        ),
    ]
