# Generated by Django 3.1.5 on 2021-01-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_highlight_title_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleseriespage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='articleseriespage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleseriespage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medialandingpage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='medialandingpage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medialandingpage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
