# Generated by Django 3.1.7 on 2021-04-19 17:37

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contentpage_authors_editors_orderable'),
        ('articles', '0007_alter_featured_article_core_contentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleseriespage',
            name='series_items',
        ),
        migrations.CreateModel(
            name='ArticleSeriesPageSeriesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category_title', models.CharField(blank=True, max_length=255)),
                ('article_series_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_items', to='articles.articleseriespage')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.contentpage', verbose_name='Series Item')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
