# Generated by Django 3.1.7 on 2021-05-05 17:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_use_custom_image_model'),
        ('articles', '0009_use_custom_image_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='cigi_people_mentioned',
        ),
        migrations.CreateModel(
            name='ArticlePagePersonMentioned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('article_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='cigi_people_mentioned', to='articles.articlepage')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personpage', verbose_name='Person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
