# Generated by Django 3.1.4 on 2020-12-16 15:18

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_create_recommended_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', streams.blocks.AuthorBlock(page_type=['people.PersonPage'], required=True)), ('external_author', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
