# Generated by Django 3.1.4 on 2020-12-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('articles', '0011_create_inline_video_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelandingpagefeaturedarticle',
            name='article_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Article'),
        ),
    ]
