# Generated by Django 3.2.4 on 2021-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_articlepage_image_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='articleseriespage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
    ]
