# Generated by Django 3.2.4 on 2021-12-16 15:48

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_add_feature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='series_items_description',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
