# Generated by Django 3.2.4 on 2021-12-17 16:58

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_articleseriespage_series_items_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='series_items_disclaimer',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
