# Generated by Django 3.1.5 on 2021-01-06 23:02

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_update_embedded_video_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
