# Generated by Django 3.1.5 on 2021-01-08 16:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articlepage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='featured_items',
            field=wagtail.core.fields.StreamField([('featured_item', wagtail.core.blocks.PageChooserBlock(page_type=['articles.ArticlePage', 'multimedia.MultimediaPage'], required=True))], blank=True),
        ),
    ]
