# Generated by Django 3.2.4 on 2022-04-25 14:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articleseriespageseriesitem_hide_series_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='series_videos_description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='To be displayed on video/multimedia pages of the series in place of Series Items Description', null=True),
        ),
    ]
