# Generated by Django 3.2.4 on 2022-04-22 19:43

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articleseriespageseriesitem_hide_series_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='credits_stream_field',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('people', wagtail.core.blocks.StreamBlock([('name', wagtail.core.blocks.CharBlock())]))]))], blank=True),
        ),
    ]
