# Generated by Django 3.1.5 on 2021-01-14 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('articles', '0018_medialandingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSeriesListPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Article Series List Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
