# Generated by Django 3.2.4 on 2022-04-22 19:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_articleseriespage_series_videos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='credits_stream_field',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('people', wagtail.blocks.StreamBlock([('name', wagtail.blocks.CharBlock())]))]))], blank=True),
        ),
    ]
