# Generated by Django 3.2.13 on 2022-08-18 18:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_auto_20220926_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespageseriesitem',
            name='additional_fields',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('position', wagtail.blocks.ChoiceBlock(choices=[('top', 'Top'), ('bottom', 'Bottom')]))]))], blank=True),
        ),
    ]
