# Generated by Django 4.0 on 2023-01-25 17:49

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_add_linebreak_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespage',
            name='acknowledgements',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
