# Generated by Django 3.2.15 on 2022-11-16 16:30

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_add_linebreak_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseriespageseriesitem',
            name='short_description_override',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
