# Generated by Django 3.2.18 on 2023-04-03 13:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_alter_articlepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelandingpage',
            name='featured_opinions',
            field=wagtail.fields.StreamField([('opinion', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=False))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='articlelandingpage',
            name='opinion_series_slider',
            field=wagtail.fields.StreamField([('opinion_series', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticleSeriesPage'], required=False))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='articlelandingpage',
            name='opinions_slider',
            field=wagtail.fields.StreamField([('opinion', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=False))], blank=True, null=True, use_json_field=None),
        ),
    ]
