# Generated by Django 3.2.18 on 2023-04-03 19:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20230403_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelandingpage',
            name='featured_opinions',
            field=wagtail.fields.StreamField([('row', wagtail.blocks.StructBlock([('row', wagtail.blocks.StreamBlock([('article_card', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]))])), ('column_block', wagtail.blocks.StructBlock([('column_cards', wagtail.blocks.StreamBlock([('article_card', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]))]))]))]))]))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='articlelandingpage',
            name='opinion_series_slider',
            field=wagtail.fields.StreamField([('opinion_series', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticleSeriesPage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_vertical', 'Medium Vertical'), ('large', 'Large'), ('large_full', 'Large Full')]))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='articlelandingpage',
            name='opinions_slider',
            field=wagtail.fields.StreamField([('opinion', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')]))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
