# Generated by Django 3.2.18 on 2023-09-25 16:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0033_auto_20230911_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleseriespageseriesitem',
            name='additional_fields',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('position', wagtail.blocks.ChoiceBlock(choices=[('top', 'Top'), ('bottom', 'Bottom')], required=False))]))], blank=True, use_json_field=True),
        ),
    ]
