# Generated by Django 3.2.18 on 2023-05-03 17:42

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_auto_20230403_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelandingpage',
            name='featured_opinions',
            field=wagtail.fields.StreamField([('row', wagtail.blocks.StructBlock([('row', wagtail.blocks.StreamBlock([('article_card', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_large', 'Medium Large'), ('large', 'Large')])), ('image_type', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('square', 'Square')]))])), ('column_block', wagtail.blocks.StructBlock([('column_cards', wagtail.blocks.StreamBlock([('article_card', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_large', 'Medium Large'), ('large', 'Large')])), ('image_type', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('square', 'Square')]))]))]))]))]))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AlterField(
            model_name='articlelandingpage',
            name='opinions_slider',
            field=wagtail.fields.StreamField([('opinion', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['articles.ArticlePage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny_with_image', 'Tiny with Image'), ('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_large', 'Medium Large'), ('large', 'Large')])), ('image_type', wagtail.blocks.ChoiceBlock(choices=[('landscape', 'Landscape'), ('square', 'Square')]))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
