# Generated by Django 5.0.6 on 2025-06-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_alter_articlelandingpage_body_alter_articlepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='canonical_link',
            field=models.URLField(blank=True, help_text='An external URL (https://...) or an internal URL (/interactives/2019annualreport/).', max_length=512),
        ),
    ]
