# Generated by Django 5.0.6 on 2025-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_articlepage_audio_file_articlepage_tts_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tts_voice',
            field=models.CharField(blank=True, choices=[('Joanna', 'Joanna'), ('Matthew', 'Matthew'), ('Salli', 'Salli'), ('Stephen', 'Stephen'), ('Danielle', 'Danielle'), ('Gregory', 'Gregory'), ('Ruth', 'Ruth'), ('Patrick', 'Patrick')], default='Joanna', help_text='Amazon Polly voice ID (e.g., Joanna, Matthew, Amy, Takumi).', max_length=32),
        ),
    ]
