# Generated by Django 5.0.6 on 2025-12-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_alter_articlelandingpage_body_alter_articlepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts/'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tts_enabled',
            field=models.BooleanField(default=True, help_text='Generate audio for this article.'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tts_last_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='tts_voice',
            field=models.CharField(blank=True, choices=[('Joanna', 'Joanna'), ('Matthew', 'Matthew'), ('Salli', 'Salli'), ('Stephen', 'Stephen'), ('Danielle', 'Danielle'), ('Gregory', 'Gregory'), ('Ruth', 'Ruth'), ('Patrick', 'Patrick')], default='Joanna', help_text='Amazon Polly voice ID (e.g., Joanna, Matthew, Amy, Takumi).', max_length=32),
        ),
    ]
