# Generated by Django 5.0.6 on 2025-12-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_articlepage_audio_file_articlepage_tts_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='tts_enabled',
        ),
    ]
