# Generated by Django 5.0.6 on 2026-01-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0059_remove_articlepage_tts_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='tts_voice',
            field=models.CharField(blank=True, choices=[('danielle_longform', 'Danielle - Longform'), ('ruth_generative', 'Ruth - Generative'), ('danielle_generative', 'Danielle - Generative')], default='danielle_longform', help_text='Amazon Polly voice ID', max_length=32),
        ),
    ]
