# Generated by Django 5.0.6 on 2026-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0061_alter_articlepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='hide_disclaimer',
            field=models.BooleanField(default=False, help_text='When enabled, hide disclaimer at the bottom of the page', verbose_name='Hide Disclaimer'),
        ),
    ]
