# Generated by Django 5.2 on 2026-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0066_alter_articlelandingpage_body_alter_articlepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='hide_has_disclaimer',
            field=models.BooleanField(default=False, help_text='When enabled, hide the Hub for Advanced Studies disclaimer', verbose_name='Hide HAS Disclaimer'),
        ),
    ]
