# Generated by Django 5.2 on 2026-04-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0025_alter_subscribepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFGBVSubscribePage',
            fields=[
                ('subscribepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='subscribe.subscribepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('subscribe.subscribepage',),
        ),
    ]
