# Generated by Django 5.2 on 2026-05-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0026_tfgbvsubscribepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribepage',
            name='button_help_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscribepage',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='subscribepage',
            name='consent_text',
            field=models.CharField(default='I consent to receiving electronic communications from the Centre for International Governance Innovation (CIGI), including updates, newsletters and event invitations. I understand that I may withdraw my consent at any time by clicking the unsubscribe link in any email.', max_length=500),
        ),
    ]
