# Generated by Django 5.2 on 2026-05-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0027_subscribepage_button_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepage',
            name='button_help_text',
            field=models.CharField(blank=True, help_text='The text that will appear next to the subscribe CTA button.', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscribepage',
            name='button_text',
            field=models.CharField(blank=True, help_text='Subscribe CTA button text (e.g. "Sign Up")', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscribepage',
            name='consent_text',
            field=models.CharField(default='I consent to receiving electronic communications from the Centre for International Governance Innovation (CIGI), including updates, newsletters and event invitations. I understand that I may withdraw my consent at any time by clicking the unsubscribe link in any email.', help_text='The text that will appear next to the consent checkbox on the subscribe form.', max_length=500),
        ),
    ]
