# Generated by Django 5.2 on 2026-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0028_alter_subscribepage_button_help_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepage',
            name='button_text',
            field=models.CharField(blank=True, default='Sign Up', help_text='Subscribe CTA button text (e.g. "Sign Up")', max_length=50),
        ),
    ]
