# Generated by Django 5.2 on 2026-05-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0029_alter_subscribepage_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribepage',
            name='button_text',
            field=models.CharField(blank=True, help_text='Subscribe CTA button text (e.g. "Sign Up")', max_length=50),
        ),
    ]
