# The name of this app. Must be unique within a project.
name: cigionline

# The runtime the application uses. The 'type' key defines the base container
# image that will be used to run the application. There is a separate base
# container image for each primary language for the application,
# in multiple versions. Check the Python documentation
# (https://docs.platform.sh/languages/python.html#supported-versions)
# to find the supported versions for the 'python' type.
type: 'python:3.12'

dependencies:
  nodejs:
    n: '*'

variables:
  env:
    N_PREFIX: /app/.global

# The following block defines a single writable directory, 'web/uploads'
# The 'source' specifies where the writable mount is. The 'local' source
# indicates that the mount point will point to a local directory on the
# application container. The 'source_path' specifies the subdirectory
# from within the source that the mount should point at.
mounts:
  'web/uploads':
    source: local
    source_path: uploads

# The size of the persistent disk of the application (in MB).
disk: 256

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form '<service name>:<endpoint name>'.
relationships:
  elasticsearch: 'elasticsearch:elasticsearch'
  redis: 'redis:redis'
  postgresql: 'postgresql:postgresql'

hooks:
  build: |
    pip install -r requirements.txt
  # npm commands:
  # n auto
  # hash -r
  # npm install
  # npm start
  deploy: |
    python manage.py migrate
    python manage.py collectstatic --noinput

web:
  commands:
    start: 'gunicorn cigionline.wsgi:application --bind 0.0.0.0:$PORT'
