language: python
python:
  - "3.7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - pip --version
  - python --version
  - psql --version
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
  - psql -c "CREATE DATABASE cigionline;" -U postgres
  - python manage.py migrate
script:
  - python manage.py test
