language: python
python:
  - "3.6"
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
env:
  global:
    - PGPORT=5433
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
install:
  - pip install -r requirements.txt
before_script:
  - sleep 10
  - psql -c "CREATE DATABASE cigionline;" -U postgres
  - python manage.py migrate
script:
  - python manage.py test
