---
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - nvm install 12.16.1
  - nvm alias default 12.16.1
  - pip --version
  - python --version
  - psql --version
  - npm --version
  - node --version
install:
  - pip install -r requirements.txt
  - npm yarn -g
  - yarn
  - yarn build:prod
before_script:
  - psql -c "CREATE DATABASE cigionline;" -U postgres
  - psql -c "CREATE ROLE cigi LOGIN PASSWORD 'cigi' superuser;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls
