# Generated by Django 3.0.3 on 2020-02-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page'},
        ),
    ]
