# Generated by Django 3.1.1 on 2020-09-24 11:59

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_themes'),
    ]

    operations = [
        UnaccentExtension(),
    ]
