# Generated by Django 3.1.7 on 2021-03-02 18:38

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_themes'),
    ]

    operations = [
        UnaccentExtension(),
    ]
