# Generated by Django 3.1.7 on 2021-03-10 16:29

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_topicpagefeaturedpage'),
        ('core', '0005_activate_pg_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='content_pages', to='research.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='content_pages', to='research.TopicPage'),
        ),
    ]
