# Generated by Django 3.1.5 on 2021-01-18 22:47

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_populate_themes'),
    ]

    operations = [
        UnaccentExtension(),
    ]
