# Generated by Django 3.1.1 on 2020-10-24 02:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contentpage_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportpage',
            name='search_terms',
            field=wagtail.core.fields.StreamField([('search_term', wagtail.core.blocks.CharBlock())], blank=True, help_text='A list of search terms for which this page will be elevated in the search results.'),
        ),
    ]
