# Generated by Django 3.1.6 on 2021-02-12 14:58

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_add_hero_stream_blocks'),
        ('core', '0008_add_hero_stream_blocks'),
        ('articles', '0011_remove_articlepage_projects'),
        ('events', '0004_remove_eventpage_projects'),
        ('multimedia', '0005_remove_multimediapage_projects'),
        ('publications', '0007_remove_publicationpage_publicationseriespage_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='research.ProjectPage'),
        ),
    ]
