# Generated by Django 3.0.7 on 2020-08-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('core', '0013_update_block_quote_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='feature_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='image_feature',
            field=models.ForeignKey(blank=True, help_text='Image used when featuring on landing pages such as the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Feature image'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
