# Generated by Django 3.1.4 on 2020-12-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_homepagefeaturedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportpage',
            name='drupal_node_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
