# Generated by Django 3.2.13 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_increase_feature_subtitle_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='twentiethpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False),
        ),
    ]
