# Generated by Django 4.0 on 2023-03-08 18:21

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0024_issuelistpage_issuepage_and_more'),
        ('core', '0025_auto_20221214_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='issues',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='content_pages', to='research.IssuePage'),
        ),
    ]
