# Generated by Django 3.2.18 on 2023-09-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('core', '0027_auto_20230911_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='AframePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Aframe Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
