# Generated by Django 3.2.18 on 2024-05-24 19:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20240209_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
