# Generated by Django 3.2.18 on 2024-06-17 20:44

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0041_countrylistpage_countrypage'),
        ('core', '0031_auto_20240209_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpage',
            name='countries',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='content_pages', to='research.CountryPage'),
        ),
    ]
