# Generated by Django 3.2.18 on 2024-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20240619_1412'),
        ('core', '0032_contentpage_countries'),
    ]

    operations = [
    ]
