# Generated by Django 5.0.6 on 2025-05-26 15:51

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_basicpage_body_alter_fundingpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='themed_content',
            field=wagtail.fields.StreamField([('sovereign_canada_rationale', wagtail.blocks.StructBlock([('documents', wagtail.blocks.StreamBlock([('document', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=False)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('large', 'Large')]))], required=True))], required=True))]))], blank=True),
        ),
    ]
