# Generated by Django 5.0.6 on 2025-06-04 16:38

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_basicpage_themed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='themed_content',
            field=wagtail.fields.StreamField([('sovereign_canada_rationale', wagtail.blocks.StructBlock([('documents', wagtail.blocks.StreamBlock([('document', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(required=False)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('large', 'Large')]))], required=True))], required=True))])), ('sovereign_canada_dashboard', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('categories', wagtail.blocks.StreamBlock([('category', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the category.', required=True)), ('files', wagtail.blocks.StreamBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(help_text='File to be displayed in the category.', required=True))], required=False))], required=True))], required=True))]))], blank=True),
        ),
    ]
