# Generated by Django 5.0.6 on 2025-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_basicpage_body_alter_fundingpage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth0AccessRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
