# Generated by Django 5.0.6 on 2025-11-04 16:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_basicpage_body_alter_fundingpage_body_and_more'),
        ('images', '0005_cigionlineimage_description'),
        ('menus', '0003_increase_menu_item_title_length'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailFormSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients_raw', models.TextField(blank=True, help_text='Enter one email per line (or comma separated). Example:\neditor@example.com\nwebmaster@example.org')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Email form',
            },
        ),
        migrations.CreateModel(
            name='FacilityRentalsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_link', wagtail.fields.StreamField([('hero_link', 2), ('hero_document', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use a font-awesome icon name such as fa-envelope', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('hero_link_text', 0), ('hero_link_url', 0), ('hero_link_icon', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('hero_link_text', 0), ('hero_link_document', 3), ('hero_link_icon', 1)]], {})}, help_text='Text with link to url, email or document and optional icon that appears below the page title in the hero section.')),
                ('subtitle', wagtail.fields.RichTextField(blank=True)),
                ('feature_subtitle', models.CharField(blank=True, max_length=500)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_url', models.URLField(blank=True)),
                ('search_terms', wagtail.fields.StreamField([('search_term', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {})}, help_text='A list of search terms for which this page will be elevated in the search results.')),
                ('search_result_description', models.CharField(blank=True, help_text='Text that is displayed when this page appears in search results', max_length=1024, null=True)),
                ('exclude_from_search', models.BooleanField(default=False)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('block_quote', 4), ('embedded_multimedia', 6), ('embedded_video', 8), ('image', 11), ('inline_video', 12), ('paragraph', 13), ('slider_gallery', 18), ('table_v2', 20), ('text_background_block', 21), ('persons_list_block', 25), ('publications_list_block', 29), ('additional_pages_block', 32), ('files_block', 36), ('collapsible_paragraph_block', 41)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('quote_author', 1), ('author_title', 1), ('image', 2), ('link_url', 3), ('link_text', 1)]], {}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.StructBlock', [[('multimedia_url', 5), ('title', 1)]], {}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('landscape', 'Landscape'), ('square', 'Square')]}), 8: ('wagtail.blocks.StructBlock', [[('video_url', 5), ('caption', 1), ('image', 2), ('aspect_ratio', 7)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 10: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 9), ('hide_image_caption', 10), ('link', 3)]], {}), 12: ('streams.blocks.InlineVideoBlock', (), {'page_type': ['multimedia.MultimediaPage']}), 13: ('streams.blocks.ParagraphBlock', (), {}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('image', 14), ('caption', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('slide', 16)]], {'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 1), ('slides', 17)]], {}), 19: ('streams.blocks.TableStreamBlock', (), {'required': True}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('table', 19)]], {}), 21: ('streams.blocks.TextBackgroundBlock', (), {'features': ['bold', 'italic', 'link']}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full_bio', 'Full Biography'), ('short_bio', 'Short Biography')], 'help_text': "Select the field from the person's page to populate their biography in this block. Default to 'Full Biography'.", 'max_choices': 1, 'required': False, 'verbose_name': 'Biography Source Field'}), 23: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': True}), 24: ('wagtail.blocks.StreamBlock', [[('person', 23)]], {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('title', 1), ('bio_source_field', 22), ('persons', 24), ('cohort', 1)]], {}), 26: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a publication type to automatically populate with this type of publications.', 'page_type': ['publications.PublicationTypePage'], 'required': False}), 27: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['publications.PublicationPage'], 'required': True}), 28: ('wagtail.blocks.StreamBlock', [[('publication', 27)]], {'required': False}), 29: ('wagtail.blocks.StructBlock', [[('title', 1), ('publication_type', 26), ('publications', 28)]], {}), 30: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 31: ('wagtail.blocks.StreamBlock', [[('page', 30)]], {'required': True}), 32: ('wagtail.blocks.StructBlock', [[('pages', 31)]], {}), 33: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 34: ('wagtail.blocks.StructBlock', [[('file', 33), ('title', 1)]], {'required': True}), 35: ('wagtail.blocks.StreamBlock', [[('file', 34)]], {'required': True}), 36: ('wagtail.blocks.StructBlock', [[('files', 35)]], {}), 37: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If checked, the paragraph will be collapsed by default.', 'required': False}), 38: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Optional title for the collapsible paragraph.', 'required': False}), 39: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Select the heading type for the title.'}), 40: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'dropcap', 'endofarticle', 'paragraph_heading', 'h2', 'h3', 'h4', 'hr', 'image', 'italic', 'underline', 'link', 'ol', 'subscript', 'superscript', 'ul', 'anchor', 'rtl'], 'required': True}), 41: ('wagtail.blocks.StructBlock', [[('collapsed', 37), ('title', 38), ('title_type', 39), ('paragraph', 40)]], {})})),
                ('related_files', wagtail.fields.StreamField([('file', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})})),
                ('image_banner', models.ForeignKey(blank=True, help_text='A banner image to be displayed as background of the hero section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image')),
                ('image_feature', models.ForeignKey(blank=True, help_text='Image used when featuring on landing pages such as the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Feature image')),
                ('image_hero', models.ForeignKey(blank=True, help_text='A large image to be displayed prominently on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Hero Image')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
                ('submenu', models.ForeignKey(blank=True, help_text='Select a submenu to appear in the right section of the hero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.menu', verbose_name='Submenu')),
            ],
            options={
                'verbose_name': 'Facility Rentals Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
