# Generated by Django 5.2 on 2026-05-27 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_twentyfifthpagesingleton'),
        ('wagtailmedia', '0005_alter_media_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='twentyfifthpagesingleton',
            name='splash_video',
            field=models.ForeignKey(blank=True, help_text='Full-screen background video shown before the page content.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Splash Video'),
        ),
    ]
