# Generated by Django 5.2 on 2026-05-28 19:13

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_twentyfifthpagesingleton_history_timeline_and_more'),
        ('events', '0055_mailchimp_tag_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwentyFifthPageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.eventpage', verbose_name='Event')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_events', to='core.twentyfifthpagesingleton')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
