# Generated by Django 5.2 on 2026-06-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_twentyfifthpageevent'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='twentyfifthpagesingleton',
            name='splash_image',
            field=models.ForeignKey(blank=True, help_text='Still image shown before the splash video loads, and used instead of video on mobile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Splash Still Image'),
        ),
    ]
