# Generated by Django 5.2 on 2026-06-02 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_twentyfifthpagesingleton_splash_image'),
        ('images', '0005_cigionlineimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twentyfifthpagesingleton',
            name='splash_image',
            field=models.ForeignKey(blank=True, help_text='Still image shown before the splash video loads, and used instead of video on mobile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Splash Still Image'),
        ),
    ]
