# Generated by Django 5.2 on 2026-07-10 13:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_humananalysisstandardpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='humananalysisstandardpage',
            name='conversion',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('streams.blocks.ParagraphBlock', (), {})}),
        ),
        migrations.AddField(
            model_name='humananalysisstandardpage',
            name='policy_download',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('streams.blocks.ParagraphBlock', (), {})}),
        ),
    ]
