# Generated by Django 5.2 on 2026-07-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_humananalysisstandardpage_conversion_and_more'),
        ('images', '0005_cigionlineimage_description'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='humananalysisstandardpage',
            name='big_has_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Big HAS image'),
        ),
        migrations.AddField(
            model_name='humananalysisstandardpage',
            name='policy_download_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Policy download PDF'),
        ),
        migrations.AddField(
            model_name='humananalysisstandardpage',
            name='small_has_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Small HAS image'),
        ),
    ]
