# Generated by Django 5.2 on 2026-09-03 22:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_humananalysisstandardpage_big_has_image_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwentyFifthFeatureLandingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('pages', wagtail.fields.StreamField([('featured_page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {})}, verbose_name='Featured Pages')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
