# Generated by Django 5.2 on 2026-10-07 17:22

import uuid

import wagtail.fields
from django.db import migrations


def move_sections_into_body(apps, schema_editor):
    Page = apps.get_model('core', 'HumanAnalysisStandardPage')

    for page in Page.objects.iterator():
        body = list(page.body.raw_data)

        if page.conversion:
            body.append({
                'type': 'conversion',
                'value': {'content': list(page.conversion.raw_data)},
                'id': str(uuid.uuid4()),
            })

        if page.policy_download or page.policy_download_pdf_id:
            body.append({
                'type': 'policy_download',
                'value': {
                    'content': list(page.policy_download.raw_data),
                    'pdf': page.policy_download_pdf_id,
                },
                'id': str(uuid.uuid4()),
            })

        if page.small_has_image_id or page.big_has_image_id:
            body.append({
                'type': 'has_image_pair',
                'value': {
                    'small_image': page.small_has_image_id,
                    'big_image': page.big_has_image_id,
                },
                'id': str(uuid.uuid4()),
            })

        page.body = body
        page.save(update_fields=['body'])


def move_sections_out_of_body(apps, schema_editor):
    Page = apps.get_model('core', 'HumanAnalysisStandardPage')

    for page in Page.objects.iterator():
        body = []
        conversion = []
        policy_download = []
        field_values = {
            'policy_download_pdf_id': None,
            'small_has_image_id': None,
            'big_has_image_id': None,
        }

        for block in page.body.raw_data:
            if block['type'] == 'conversion':
                conversion.extend(block['value'].get('content', []))
            elif block['type'] == 'policy_download':
                policy_download.extend(block['value'].get('content', []))
                field_values['policy_download_pdf_id'] = block['value'].get('pdf')
            elif block['type'] == 'has_image_pair':
                field_values['small_has_image_id'] = block['value'].get('small_image')
                field_values['big_has_image_id'] = block['value'].get('big_image')
            else:
                body.append(block)

        page.body = body
        page.conversion = conversion
        page.policy_download = policy_download
        for field, value in field_values.items():
            setattr(page, field, value)
        page.save(update_fields=[
            'body',
            'conversion',
            'policy_download',
            'policy_download_pdf',
            'small_has_image',
            'big_has_image',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_twentyfifthpagesingleton_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humananalysisstandardpage',
            name='body',
            field=wagtail.fields.StreamField([('block_quote', 4), ('button', 8), ('embedded_multimedia', 10), ('embedded_video', 12), ('image', 15), ('inline_video', 16), ('paragraph', 17), ('slider_gallery', 22), ('table_v2', 24), ('text_background_block', 25), ('persons_list_block', 29), ('publications_list_block', 33), ('additional_pages_block', 36), ('files_block', 40), ('collapsible_paragraph_block', 45), ('promotion_block_stream_block', 47), ('text_border_block', 48), ('publication_visual_elements', 53), ('conversion', 55), ('policy_download', 57), ('has_image_pair', 58)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 0), ('quote_author', 1), ('author_title', 1), ('image', 2), ('link_url', 3), ('link_text', 1)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use font-awesome classes such as fa-solid fa-download', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('text', 5), ('page', 6), ('url', 3), ('icon', 7)]], {}), 9: ('wagtail.blocks.URLBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('multimedia_url', 9), ('title', 1)]], {}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('landscape', 'Landscape'), ('square', 'Square')]}), 12: ('wagtail.blocks.StructBlock', [[('video_url', 9), ('caption', 1), ('image', 2), ('aspect_ratio', 11)]], {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 14: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 15: ('wagtail.blocks.StructBlock', [[('image', 13), ('hide_image_caption', 14), ('link', 3)]], {}), 16: ('streams.blocks.InlineVideoBlock', (), {'page_type': ['multimedia.MultimediaPage']}), 17: ('streams.blocks.ParagraphBlock', (), {}), 18: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 19: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 18), ('caption', 19)]], {}), 21: ('wagtail.blocks.StreamBlock', [[('slide', 20)]], {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 1), ('slides', 21)]], {}), 23: ('streams.blocks.TableStreamBlock', (), {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('title', 1), ('table', 23)]], {}), 25: ('streams.blocks.TextBackgroundBlock', (), {'features': ['bold', 'italic', 'link']}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full_bio', 'Full Biography'), ('short_bio', 'Short Biography')], 'help_text': "Select the field from the person's page to populate their biography in this block. Default to 'Full Biography'.", 'max_choices': 1, 'required': False, 'verbose_name': 'Biography Source Field'}), 27: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': True}), 28: ('wagtail.blocks.StreamBlock', [[('person', 27)]], {'required': True}), 29: ('wagtail.blocks.StructBlock', [[('title', 1), ('bio_source_field', 26), ('persons', 28), ('cohort', 1)]], {}), 30: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select a publication type to automatically populate with this type of publications.', 'page_type': ['publications.PublicationTypePage'], 'required': False}), 31: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['publications.PublicationPage'], 'required': True}), 32: ('wagtail.blocks.StreamBlock', [[('publication', 31)]], {'required': False}), 33: ('wagtail.blocks.StructBlock', [[('title', 1), ('publication_type', 30), ('publications', 32)]], {}), 34: ('wagtail.blocks.PageChooserBlock', (), {'required': True}), 35: ('wagtail.blocks.StreamBlock', [[('page', 34)]], {'required': True}), 36: ('wagtail.blocks.StructBlock', [[('pages', 35)]], {}), 37: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 38: ('wagtail.blocks.StructBlock', [[('file', 37), ('title', 1)]], {'required': True}), 39: ('wagtail.blocks.StreamBlock', [[('file', 38)]], {'required': True}), 40: ('wagtail.blocks.StructBlock', [[('files', 39)]], {}), 41: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'If checked, the paragraph will be collapsed by default.', 'required': False}), 42: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Optional title for the collapsible paragraph.', 'required': False}), 43: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'help_text': 'Select the heading type for the title.'}), 44: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'dropcap', 'endofarticle', 'paragraph_heading', 'h2', 'h3', 'h4', 'hr', 'image', 'italic', 'underline', 'link', 'ol', 'subscript', 'superscript', 'ul', 'anchor', 'rtl'], 'required': True}), 45: ('wagtail.blocks.StructBlock', [[('collapsed', 41), ('title', 42), ('title_type', 43), ('paragraph', 44)]], {}), 46: ('wagtail.snippets.blocks.SnippetChooserBlock', ('promotions.PromotionBlock',), {}), 47: ('wagtail.blocks.StructBlock', [[('block', 46)]], {}), 48: ('wagtail.blocks.StructBlock', [[('text', 0), ('border_colour', 1)]], {}), 49: ('wagtail.blocks.CharBlock', (), {'max_length': 140, 'required': True}), 50: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full width'), ('icon', 'Icon')]}), 51: ('wagtail.blocks.StructBlock', [[('label', 49), ('image', 13), ('display_size', 50)]], {}), 52: ('wagtail.blocks.ListBlock', (51,), {'required': True}), 53: ('wagtail.blocks.StructBlock', [[('heading', 1), ('items', 52)]], {}), 54: ('wagtail.blocks.StreamBlock', [[('paragraph', 17)]], {'required': False}), 55: ('wagtail.blocks.StructBlock', [[('content', 54)]], {}), 56: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 57: ('wagtail.blocks.StructBlock', [[('content', 54), ('pdf', 56)]], {}), 58: ('wagtail.blocks.StructBlock', [[('small_image', 2), ('big_image', 2)]], {})}),
        ),
        migrations.RunPython(move_sections_into_body, move_sections_out_of_body),
        migrations.RemoveField(
            model_name='humananalysisstandardpage',
            name='big_has_image',
        ),
        migrations.RemoveField(
            model_name='humananalysisstandardpage',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='humananalysisstandardpage',
            name='policy_download',
        ),
        migrations.RemoveField(
            model_name='humananalysisstandardpage',
            name='policy_download_pdf',
        ),
        migrations.RemoveField(
            model_name='humananalysisstandardpage',
            name='small_has_image',
        ),
    ]
