# Generated by Django 3.1.7 on 2021-03-16 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20210315_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='multimedia_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='multimedia.multimediaseriespage'),
        ),
    ]
