# Generated by Django 3.1.5 on 2021-01-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_auto_20210118_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedialistpage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='multimedialistpage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multimedialistpage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multimediapage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='multimediapage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multimediapage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multimediaseriespage',
            name='hero_link_icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='multimediaseriespage',
            name='hero_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='multimediaseriespage',
            name='hero_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
