# Generated by Django 3.1.1 on 2020-11-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('multimedia', '0002_multimediapage_article_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='companion_essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Companion essay'),
        ),
    ]
