# Generated by Django 3.1.6 on 2021-02-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_add_mm_promotion_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimediapage',
            name='projects',
        ),
    ]
