# Generated by Django 3.1.4 on 2020-12-08 18:24

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_create_chart_stream_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='speakers',
            field=wagtail.core.fields.StreamField([('speaker', streams.blocks.SpeakersBlock(page_type=['people.PersonPage'], required=True)), ('external_speaker', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
