# Generated by Django 3.2.4 on 2021-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_use_custom_image_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='multimedia_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='video', max_length=8),
        ),
    ]
