# Generated by Django 3.2.4 on 2021-10-20 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('multimedia', '0006_alter_multimediapage_multimedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='image_poster',
            field=models.ForeignKey(blank=True, help_text='A poster image used in feature sections', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Poster Image'),
        ),
    ]
