# Generated by Django 3.2.4 on 2021-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0009_auto_20211103_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='multimediaseriespage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
    ]
