# Generated by Django 3.1.5 on 2021-01-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('multimedia', '0014_update_embedded_video_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='image_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Banner Image'),
        ),
    ]
