# Generated by Django 3.2.15 on 2022-11-22 16:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0014_alter_multimedialistpage_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
