# Generated by Django 3.2.15 on 2022-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0015_multimediapage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='length',
            field=models.CharField(blank=True, help_text='The length of the multimedia source in minutes and seconds (e.g. 1:23).', max_length=8, verbose_name='Length'),
        ),
    ]
