# Generated by Django 4.0 on 2023-01-31 17:48

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0018_multimedialistpage_featured_multimedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedialistpage',
            name='big_tech_episodes',
            field=wagtail.fields.StreamField([('multimedia', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['multimedia.MultimediaPage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')])), ('multimedia_type', wagtail.blocks.ChoiceBlock(choices=[('video', 'Video'), ('podcast', 'Podcast')]))]))], blank=True, null=True, use_json_field=None, verbose_name='Big Tech Episodes'),
        ),
    ]
