# Generated by Django 4.0 on 2023-03-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0019_multimedialistpage_big_tech_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='The URL of the multimedia source from Vimeo.', verbose_name='Vimeo URL'),
        ),
    ]
