# Generated by Django 4.0 on 2023-03-16 14:30

from django.db import migrations
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0020_multimediapage_vimeo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='vimeo_url',
            field=wagtail.fields.StreamField([('vimeo_embed', wagtail.embeds.blocks.EmbedBlock(max_height=990, max_width=1440))], blank=True, use_json_field=None),
        ),
    ]
