# Generated by Django 3.2.18 on 2023-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0021_alter_multimediapage_vimeo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='vimeo_url',
            field=models.URLField(blank=True, help_text='The URL of the multimedia source from Vimeo.', verbose_name='Vimeo URL'),
        ),
    ]
