# Generated by Django 3.2.18 on 2023-05-02 13:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0022_alter_multimediapage_vimeo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedialistpage',
            name='featured_multimedia_pages',
            field=wagtail.fields.StreamField([('multimedia_page', wagtail.blocks.PageChooserBlock('multimedia.MultimediaPage'))], blank=True, help_text='Limit 2 items - the first item will appear at the top of the page and the second will appear as the third row in the listing.', null=True, use_json_field=None, verbose_name='Featured Multimedia Pages'),
        ),
    ]
