# Generated by Django 3.2.18 on 2024-04-24 17:56

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0024_multimediaseriespage_featured_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaseriespage',
            name='podcast_subscribe_buttons',
            field=wagtail.fields.StreamField([('podcast_subscribe_button', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, help_text='A list of subscribe links to various podcast providers', use_json_field=True, verbose_name='Podcast Subscribe Buttons'),
        ),
    ]
