# Generated by Django 3.2.18 on 2024-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0025_alter_multimediaseriespage_podcast_subscribe_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaseriespage',
            name='podcast_live',
            field=models.BooleanField(default=False),
        ),
    ]
