# Generated by Django 3.2.18 on 2024-04-26 15:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0026_multimediaseriespage_podcast_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaseriespage',
            name='podcast_hosts',
            field=wagtail.fields.StreamField([('podcast_host', wagtail.blocks.StructBlock([('host', wagtail.blocks.PageChooserBlock(page_type=['people.PersonPage'], required=True)), ('bio', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, help_text='A list of hosts for the podcast series', use_json_field=True, verbose_name='Podcast Hosts'),
        ),
        migrations.AlterField(
            model_name='multimediaseriespage',
            name='podcast_subscribe_buttons',
            field=wagtail.fields.StreamField([('podcast_subscribe_button', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock(required=True)), ('url', wagtail.blocks.URLBlock(required=True))]))], blank=True, help_text='A list of subscribe links to various podcast providers', use_json_field=True, verbose_name='Podcast Subscribe Buttons'),
        ),
    ]
