# Generated by Django 3.2.18 on 2024-04-30 17:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0028_auto_20240430_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='podcast_chapters',
            field=wagtail.fields.StreamField([('podcast_chapter', wagtail.blocks.StructBlock([('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('timestamp', wagtail.blocks.StructBlock([('hours', wagtail.blocks.IntegerBlock(min_value=0, required=True)), ('minutes', wagtail.blocks.IntegerBlock(max_value=59, min_value=0, required=True)), ('seconds', wagtail.blocks.IntegerBlock(max_value=59, min_value=0, required=True))]))]))], blank=True, help_text='A list of chapters for the podcast', use_json_field=True, verbose_name='Podcast Chapters'),
        ),
    ]
