# Generated by Django 3.2.18 on 2024-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0030_alter_multimediaseriespage_podcast_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediapage',
            name='podcast_recording_date',
            field=models.DateField(blank=True, null=True, verbose_name='Recording Date'),
        ),
    ]
