# Generated by Django 3.2.18 on 2024-05-21 16:09

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0031_multimediapage_podcast_recording_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='podcast_guests',
            field=wagtail.fields.StreamField([('guest', wagtail.blocks.CharBlock(required=True)), ('guest_page', wagtail.blocks.StructBlock([('guest', wagtail.blocks.CharBlock(required=False)), ('guest_page', wagtail.blocks.PageChooserBlock(page_type=['people.PersonPage'], required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('bio', wagtail.blocks.RichTextBlock(required=False))]))], blank=True, help_text='A list of guests for the podcast. If the guest has a page on the site, you can link to it here.', use_json_field=True),
        ),
    ]
