# Generated by Django 3.2.18 on 2024-05-22 13:17

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0033_alter_multimediapage_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='transcript',
            field=wagtail.fields.StreamField([('accordion', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'h3', 'h4', 'italic', 'link', 'ol', 'ul'], required=True))])), ('read_more', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'h3', 'h4', 'italic', 'link', 'ol', 'ul'], required=True))])), ('transcript_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('timestamp', wagtail.blocks.StructBlock([('hours', wagtail.blocks.IntegerBlock(min_value=0, required=False)), ('minutes', wagtail.blocks.IntegerBlock(max_value=59, min_value=0, required=False)), ('seconds', wagtail.blocks.IntegerBlock(max_value=59, min_value=0, required=False))], help_text='Enter the timestamp of the transcript if it corresponds to a specific time in the podcast.', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
