# Generated by Django 3.2.18 on 2024-06-10 14:13

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0034_alter_multimediapage_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimediaseriespage',
            name='credits',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
