# Generated by Django 5.0.6 on 2024-08-23 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0025_auto_20240709_1057'),
        ('multimedia', '0035_multimediaseriespage_credits'),
    ]

    operations = [
    ]
