# Generated by Django 5.2 on 2026-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0044_alter_multimedialistpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediapage',
            name='multimedia_url',
            field=models.URLField(blank=True, help_text='The URL of the multimedia source from YouTube or Simplecast.', max_length=500, verbose_name='Multimedia URL'),
        ),
    ]
