# Generated by Django 3.2.18 on 2024-02-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20240111_0946'),
        ('newsletters', '0013_alter_newsletterlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme'),
        ),
    ]
