# Generated by Django 3.1.7 on 2021-04-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('annual_reports', '0005_update_table_stream_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreportlistpage',
            name='image_hero',
            field=models.ForeignKey(blank=True, help_text='A large image to be displayed prominently on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='annualreportpage',
            name='image_feature',
            field=models.ForeignKey(blank=True, help_text='Image used when featuring on landing pages such as the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Feature image'),
        ),
        migrations.AlterField(
            model_name='annualreportpage',
            name='image_poster',
            field=models.ForeignKey(blank=True, help_text='Poster sized image that is displayed in the featured section on the Annual Reports page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Cover image'),
        ),
    ]
