# Generated by Django 3.1.13 on 2021-08-04 10:13

from django.db import migrations, models
import django.db.models.deletion
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('people', '0006_use_custom_image_model'),
        ('annual_reports', '0006_use_custom_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='TabbedSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('tabs', wagtail.core.fields.StreamField([('tab', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('body', wagtail.core.blocks.StreamBlock([('paragraph', streams.blocks.ParagraphBlock()), ('table', streams.blocks.TableStreamBlock())]))]))])),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='SummarySlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('acknowledgement_message', wagtail.core.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock())])),
                ('acknowledged_groups', wagtail.core.fields.StreamField([('acknowledged_group', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('people', wagtail.core.blocks.StreamBlock([('page', streams.blocks.PersonBlock('people.PersonPage'))]))]))])),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='OutputsAndActivitiesSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='MessageSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('body', wagtail.core.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock())])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_slides_as_author', to='people.personpage', verbose_name='Author')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ContentSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('social_title', models.CharField(blank=True, max_length=255)),
                ('social_description', models.CharField(blank=True, max_length=255)),
                ('quote', wagtail.core.fields.StreamField([('quote', wagtail.core.blocks.StructBlock([('message', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=True)), ('subtitle', streams.blocks.ParagraphBlock(features=['bold', 'italic', 'link'], required=False))]))], blank=True)),
                ('body', wagtail.core.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock())])),
                ('links', wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('url', wagtail.core.blocks.URLBlock(required=True)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('EVENT', 'Event'), ('MEDIA', 'Media'), ('OPINION', 'Opinion'), ('PODCAST', 'Podcast'), ('PUBLICATION', 'Publication'), ('VIDEO', 'Video'), ('EXPERTS', 'Experts'), ('SUBSCRIBE', 'Subscribe'), ('PARTNERS', 'Partners')], verbose_name='Type'))]))], blank=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Background image')),
                ('background_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Background video')),
                ('image_social', models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
