# Generated by Django 3.2.4 on 2021-10-06 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0007_auto_20210727_1424'),
        ('annual_reports', '0007_slidepages'),
    ]

    operations = [
    ]
