# Generated by Django 3.2.4 on 2021-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0007_auto_20210727_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportpage',
            name='feature_url',
            field=models.URLField(blank=True),
        ),
    ]
