# Generated by Django 3.2.13 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0009_increase_feature_subtitle_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportlistpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annualreportpage',
            name='exclude_from_search',
            field=models.BooleanField(default=False),
        ),
    ]
