# Generated by Django 3.2.15 on 2022-09-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0010_auto_20220713_1036'),
        ('annual_reports', '0010_auto_20220812_1021'),
    ]

    operations = [
    ]
