# Generated by Django 3.2.4 on 2022-03-20 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0010_outputs_and_activities_slide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputsandactivitiesslidepage',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='outputsandactivitiesslidepage',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
