# Generated by Django 4.0 on 2022-12-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0012_alter_annualreportlistpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreportlistpage',
            name='featured_reports',
        ),
        migrations.AddField(
            model_name='annualreportpage',
            name='report_interactive_fr',
            field=models.CharField(blank=True, help_text='Internal path to the FR version of the interactive report. Example: /interactives/2019annualreport/fr', max_length=255),
        ),
    ]
