# Generated by Django 5.0.6 on 2025-02-14 15:15

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0020_alter_annualreportlistpage_body'),
        ('images', '0004_alter_cigionlinerendition_file'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReportSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('slide_title', models.CharField(help_text='Title of the slide', max_length=255)),
                ('slide_content', wagtail.fields.RichTextField(blank=True, help_text='Content of the slide')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnnualReportSPAPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('feature_subtitle', models.CharField(blank=True, max_length=500)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_url', models.URLField(blank=True)),
                ('search_terms', wagtail.fields.StreamField([('search_term', wagtail.blocks.CharBlock())], blank=True, help_text='A list of search terms for which this page will be elevated in the search results.')),
                ('search_result_description', models.CharField(blank=True, help_text='Text that is displayed when this page appears in search results', max_length=1024, null=True)),
                ('exclude_from_search', models.BooleanField(default=False)),
                ('image_feature', models.ForeignKey(blank=True, help_text='Image used when featuring on landing pages such as the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Feature image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
