# Generated by Django 5.0.6 on 2025-02-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0021_annualreportslidepage_annualreportspapage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='slide_type',
            field=models.CharField(choices=[('regular', 'Regular Slide'), ('toc', 'Table of Contents')], default='regular', help_text='Type of slide', max_length=255),
        ),
    ]
