# Generated by Django 5.0.6 on 2025-02-19 19:37

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0022_annualreportslidepage_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportspapage',
            name='slides',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('slide', wagtail.blocks.PageChooserBlock(page_type=['annual_reports.AnnualReportSlidePage'], required=True))]))], blank=True),
        ),
    ]
