# Generated by Django 5.0.6 on 2025-02-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0023_annualreportspapage_slides'),
        ('images', '0004_alter_cigionlinerendition_file'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text='Background image for the slide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_video',
            field=models.ForeignKey(blank=True, help_text='Background video for the slide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
