# Generated by Django 5.0.6 on 2025-02-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0024_annualreportslidepage_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='include_on_toc',
            field=models.BooleanField(default=True, help_text='Include this slide in the table of contents'),
        ),
    ]
