# Generated by Django 5.0.6 on 2025-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0025_annualreportslidepage_include_on_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('strategic_plan_yellow', 'Strategic Plan Yellow')], help_text='Background colour for the slide', max_length=255),
        ),
    ]
