# Generated by Django 5.0.6 on 2025-03-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0026_annualreportslidepage_background_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='slide_theme',
            field=models.CharField(choices=[('annual_report', 'Annual Report'), ('strategic_plan', 'Strategic Plan')], default='annual_report', help_text='Theme of the slide', max_length=255),
        ),
    ]
