# Generated by Django 5.0.6 on 2025-03-04 15:53

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0027_annualreportslidepage_slide_theme'),
        ('images', '0004_alter_cigionlinerendition_file'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtailmedia', '0004_duration_optional_floatfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='slide_type',
            field=models.CharField(choices=[('regular', 'Regular Slide'), ('toc', 'Table of Contents'), ('text', 'Text Slide'), ('quote', 'Quote Slide')], default='regular', help_text='Type of slide', max_length=255),
        ),
        migrations.CreateModel(
            name='StrategicPlanSlidePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('slide_title', models.CharField(help_text='Title of the slide', max_length=255)),
                ('slide_content', wagtail.fields.RichTextField(blank=True, help_text='Content of the slide')),
                ('slide_type', models.CharField(choices=[('regular', 'Regular Slide'), ('toc', 'Table of Contents'), ('text', 'Text Slide'), ('quote', 'Quote Slide')], default='regular', help_text='Type of slide', max_length=255)),
                ('slide_theme', models.CharField(choices=[('annual_report', 'Annual Report'), ('strategic_plan', 'Strategic Plan')], default='annual_report', help_text='Theme of the slide', max_length=255)),
                ('background_colour', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('strategic_plan_yellow', 'Strategic Plan Yellow')], help_text='Background colour for the slide', max_length=255)),
                ('include_on_toc', models.BooleanField(default=True, help_text='Include this slide in the table of contents')),
                ('background_image', models.ForeignKey(blank=True, help_text='Background image for the slide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage')),
                ('background_video', models.ForeignKey(blank=True, help_text='Background video for the slide', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='StrategicPlanSPAPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('feature_subtitle', models.CharField(blank=True, max_length=500)),
                ('feature_title', models.CharField(blank=True, max_length=255)),
                ('feature_url', models.URLField(blank=True)),
                ('search_terms', wagtail.fields.StreamField([('search_term', wagtail.blocks.CharBlock())], blank=True, help_text='A list of search terms for which this page will be elevated in the search results.')),
                ('search_result_description', models.CharField(blank=True, help_text='Text that is displayed when this page appears in search results', max_length=1024, null=True)),
                ('exclude_from_search', models.BooleanField(default=False)),
                ('slides', wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('slide', wagtail.blocks.PageChooserBlock(page_type=['annual_reports.AnnualReportSlidePage'], required=True))]))], blank=True)),
                ('image_feature', models.ForeignKey(blank=True, help_text='Image used when featuring on landing pages such as the home page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Feature image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
