# Generated by Django 5.0.6 on 2025-03-04 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0028_alter_annualreportslidepage_slide_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='columns',
            field=models.IntegerField(default=1, help_text='Number of columns for the slide (only for regular slides)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='wide_column',
            field=models.BooleanField(default=False, help_text='Make the column wide (only applicable if there is one column)'),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='background_colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black')], help_text='Background colour for the slide', max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='background_colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black')], help_text='Background colour for the slide', max_length=255),
        ),
    ]
