# Generated by Django 5.0.6 on 2025-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0029_strategicplanslidepage_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title Slide'), ('toc', 'Table of Contents'), ('text', 'Text Slide'), ('regular', 'Regular Slide'), ('framework', 'Framework Slide'), ('timeline', 'Timeline Slide')], default='regular', help_text='Type of slide', max_length=255),
        ),
    ]
