# Generated by Django 5.0.6 on 2025-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0030_alter_strategicplanslidepage_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='slide_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of the slide', max_length=255),
        ),
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='slide_subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of the slide', max_length=255),
        ),
    ]
