# Generated by Django 5.0.6 on 2025-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0031_annualreportslidepage_slide_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='background_colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('strategic_plan_yellow', 'Strategic Plan Yellow')], help_text='Background colour for the slide', max_length=255),
        ),
    ]
