# Generated by Django 5.0.6 on 2025-03-04 17:25

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0032_alter_strategicplanslidepage_background_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='background_colour',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('strategic_plan_yellow', 'Strategic Plan Yellow'), ('strategic_plan_grey', 'Strategic Plan Grey')], help_text='Background colour for the slide', max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicplanspapage',
            name='slides',
            field=wagtail.fields.StreamField([('slide', wagtail.blocks.StructBlock([('slide', wagtail.blocks.PageChooserBlock(page_type=['annual_reports.StrategicPlanSlidePage'], required=True))]))], blank=True),
        ),
    ]
