# Generated by Django 5.0.6 on 2025-03-05 19:57

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0033_alter_strategicplanslidepage_background_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='strategic_plan_slide_content',
            field=wagtail.fields.StreamField([('column', wagtail.blocks.RichTextBlock()), ('acknowledgements', wagtail.blocks.RichTextBlock())], blank=True, help_text='Content of the slide'),
        ),
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='slide_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Content of the slide'),
        ),
    ]
