# Generated by Django 5.0.6 on 2025-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0035_strategicplanslidepage_alignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicplanslidepage',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='strategicplanslidepage',
            name='wide_column',
        ),
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='column_size',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('large', 'Large')], help_text='Column size (only for regular slides)', max_length=255),
        ),
    ]
