# Generated by Django 5.0.6 on 2025-03-18 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0040_alter_strategicplanslidepage_strategic_plan_slide_content'),
        ('images', '0004_alter_cigionlinerendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicplanspapage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='strategicplanspapage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='strategicplanspapage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
