# Generated by Django 5.0.6 on 2025-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0041_strategicplanspapage_image_social_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='display_vertical_title',
            field=models.BooleanField(default=True, help_text='Display the title vertically'),
        ),
    ]
