# Generated by Django 5.0.6 on 2025-04-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0046_alter_strategicplanslidepage_strategic_plan_slide_content'),
        ('images', '0004_alter_cigionlinerendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_images',
            field=models.ManyToManyField(blank=True, help_text='Background images for the slide', null=True, related_name='+', to='images.cigionlineimage'),
        ),
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='background_images',
            field=models.ManyToManyField(blank=True, help_text='Background images for the slide', null=True, related_name='+', to='images.cigionlineimage'),
        ),
    ]
