# Generated by Django 5.0.6 on 2025-04-09 19:45

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0047_annualreportslidepage_background_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreportslidepage',
            name='background_images',
        ),
        migrations.RemoveField(
            model_name='strategicplanslidepage',
            name='background_images',
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='Additional background images for the slide'),
        ),
        migrations.AddField(
            model_name='strategicplanslidepage',
            name='background_images',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, help_text='Additional background images for the slide'),
        ),
    ]
