# Generated by Django 5.0.6 on 2025-06-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0022_alter_annualreportlistpage_body'),
        ('annual_reports', '0050_alter_strategicplanslidepage_strategic_plan_slide_content'),
    ]

    operations = [
    ]
