# Generated by Django 5.0.6 on 2025-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0051_merge_20250624_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicplanslidepage',
            name='alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right'), ('full', 'Full'), ('top', 'Top'), ('none', 'None')], help_text='Alignment of the columns (only for regular slides)', max_length=255),
        ),
    ]
