# Generated by Django 5.0.6 on 2025-12-22 19:18

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0055_alter_annualreportlistpage_body'),
        ('images', '0005_cigionlineimage_description'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 11), ('board', 21), ('auditor_report', 28), ('financial_position', 32), ('fund_balances', 35), ('outputs_and_activities', 39)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'red-line', 'chair-name'], 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('en', 0), ('fr', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publication', 'Publication'), ('opinion', 'Opinion'), ('video', 'Video'), ('podcast', 'Podcast'), ('event', 'Event'), ('essay series', 'Essay Series'), ('media', 'Media'), ('news release', 'News Release'), ('experts', 'Experts'), ('subscribe', 'Subscribe'), ('listen', 'Listen'), ('explore', 'Explore'), ('episode', 'Episode'), ('research', 'Research'), ('survey', 'Survey'), ('t7', 'T7'), ('website', 'Website')]}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the content type label for this content item', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the content type label for this content item in French', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this content item', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Override the title for this content item', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('type', 2), ('type_override', 3), ('type_override_fr', 4), ('page', 5), ('link_override', 6), ('title_en', 7), ('title_fr', 7)]], {}), 9: ('wagtail.blocks.StreamBlock', [[('content', 8)]], {'required': False}), 10: ('wagtail.blocks.StreamBlock', [[('paragraph_column', 1), ('content_column', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('column', 10)]], {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('board', 'Board'), ('executive', 'Executive')]}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 18: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this person', 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('name', 13), ('title', 13), ('title_line_2', 14), ('title_fr', 13), ('title_line_2_fr', 14), ('bio_en', 15), ('bio_fr', 15), ('page', 16), ('image_override', 17), ('link_override', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('member', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[('board_type', 12), ('board_members', 20)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h4'], 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 24: ('wagtail.blocks.StructBlock', [[('signature', 17), ('signature_text', 23)]], {}), 25: ('wagtail.blocks.StreamBlock', [[('paragraph', 22), ('signature', 24)]], {}), 26: ('wagtail.blocks.StructBlock', [[('en', 25), ('fr', 25)]], {}), 27: ('wagtail.blocks.StreamBlock', [[('column', 26)]], {}), 28: ('wagtail.blocks.StructBlock', [[('title_en', 14), ('title_fr', 14), ('columns', 27)]], {}), 29: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('year_label', 14), ('cash_and_cash_equivalents', 14), ('portfolio_investments', 14), ('amounts_receivable', 14), ('prepaid_expenses', 14), ('current_assets_subtotal', 14), ('property_and_equipment', 14), ('lease_inducement', 14), ('other_assets_subtotal', 14), ('total_assets', 14), ('accounts_payable_and_accrued_liabilities', 14), ('deferred_revenue', 14), ('total_liabilities', 14), ('invested_in_capital_assets', 14), ('externally_restricted', 14), ('internally_restricted', 14), ('unrestricted', 14), ('total_fund_balances', 14), ('total_liabilities_and_fund_balances', 14)]], {}), 31: ('wagtail.blocks.StructBlock', [[('year_current', 30), ('year_previous', 30)]], {}), 32: ('wagtail.blocks.StructBlock', [[('title_en', 14), ('title_fr', 14), ('description_en', 29), ('description_fr', 29), ('amounts', 31)]], {}), 33: ('wagtail.blocks.StructBlock', [[('year_label', 14), ('realized_investment_income', 14), ('unrealized_investment_gains', 14), ('other', 14), ('government_and_other_grants', 14), ('total_revenue', 14), ('research_and_conferences', 14), ('amortization', 14), ('administration', 14), ('facilities', 14), ('technical_support', 14), ('total_expenses', 14), ('excess_of_expenses_over_revenue', 14), ('fund_balances_beginning_of_year', 14), ('fund_balances_end_of_year', 14)]], {}), 34: ('wagtail.blocks.StructBlock', [[('year_current', 33), ('year_previous', 33)]], {}), 35: ('wagtail.blocks.StructBlock', [[('title_en', 14), ('title_fr', 14), ('description_en', 29), ('description_fr', 29), ('amounts', 34)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the type of output (e.g., Publication, Opinion, Video, Podcast, Event).', 'required': False}), 37: ('wagtail.blocks.StructBlock', [[('page', 5), ('title_override', 14), ('link_override', 6), ('description_override', 23), ('image_override', 17), ('type_override', 36)]], {}), 38: ('wagtail.blocks.StreamBlock', [[('output', 37)]], {}), 39: ('wagtail.blocks.StructBlock', [[('title', 14), ('outputs', 38)]], {})}, help_text='Content of the slide'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote',
            field=wagtail.fields.RichTextField(blank=True, help_text='quote for the background image'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_font_size',
            field=models.CharField(choices=[('smaller', 'Smaller'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Font size of the quote', max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_font_size_fr',
            field=models.CharField(choices=[('smaller', 'Smaller'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Font size of the quote (French)', max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_fr',
            field=wagtail.fields.RichTextField(blank=True, help_text='quote for the background image (French)'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_position',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], help_text='Position of the quote', max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='download_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='french_slide',
            field=models.BooleanField(default=True, help_text='Indicates if this slide has a French version'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='slide_title_fr',
            field=wagtail.fields.RichTextField(blank=True, help_text='Title of the slide (French)', max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='slide_title',
            field=wagtail.fields.RichTextField(help_text='Title of the slide', max_length=255),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title'), ('toc', 'Table of Contents'), ('chairs_message', "Chair's Message"), ('presidents-message', "President's Message"), ('standard', 'Standard'), ('outputs_and_activities', 'Outputs and Activities'), ('timeline', 'Timeline'), ('financials', 'Financials')], default='standard', help_text='Type of slide', max_length=255),
        ),
    ]
