# Generated by Django 5.0.6 on 2025-09-09 11:50

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0055_alter_annualreportlistpage_body'),
        ('images', '0005_cigionlineimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'h2', 'h3', 'h3', 'ol', 'ul', 'link', 'coloured']})}, help_text='Content of the slide'),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title'), ('toc', 'Table of Contents'), ('chairs_message', "Chair's Message"), ('presidents_message', "President's Message"), ('standard', 'Standard'), ('outputs_and_activities', 'Outputs and Activities'), ('timeline', 'Timeline'), ('financials', 'Financials')], default='standard', help_text='Type of slide', max_length=255),
        ),
    ]
