# Generated by Django 5.0.6 on 2025-09-12 19:19

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0058_alter_annualreportslidepage_ar_slide_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of the report - only used for title page', null=True),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 9), ('board', 14)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('en', 0), ('fr', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publication', 'Publication'), ('opinion', 'Opinion'), ('video', 'Video'), ('podcast', 'Podcast'), ('event', 'Event'), ('essay series', 'Essay Series'), ('media', 'Media'), ('news release', 'News Release'), ('experts', 'Experts'), ('subscribe', 'Subscribe'), ('listen', 'Listen'), ('explore', 'Explore')]}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this content item', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the title for this content item', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('type', 2), ('page', 3), ('link_override', 4), ('title_en', 5), ('title_fr', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('content', 6)]], {'required': False}), 8: ('wagtail.blocks.StreamBlock', [[('paragraph_column', 1), ('content_column', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('column', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('board', 'Board'), ('executive', 'Executive')]}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('name', 11), ('title', 11), ('title_fr', 11)]], {}), 13: ('wagtail.blocks.StreamBlock', [[('member', 12)]], {}), 14: ('wagtail.blocks.StructBlock', [[('board_type', 10), ('board_members', 13)]], {})}, help_text='Content of the slide'),
        ),
    ]
