# Generated by Django 5.0.6 on 2025-09-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0059_annualreportslidepage_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreportslidepage',
            name='year',
        ),
        migrations.RemoveField(
            model_name='annualreportspapage',
            name='slides',
        ),
    ]
