# Generated by Django 5.0.6 on 2025-09-15 15:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0060_remove_annualreportslidepage_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportspapage',
            name='slides',
            field=wagtail.fields.StreamField([('slide', 1)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['annual_reports.AnnualReportSlidePage'], 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('slide', 0)]], {})}),
        ),
        migrations.AddField(
            model_name='annualreportspapage',
            name='year',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
    ]
