# Generated by Django 5.0.6 on 2025-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0061_annualreportspapage_slides_annualreportspapage_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreportspapage',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
