# Generated by Django 5.0.6 on 2025-09-30 13:42

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0062_alter_annualreportspapage_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreportslidepage',
            name='background_caption',
        ),
        migrations.RemoveField(
            model_name='annualreportslidepage',
            name='background_caption_fr',
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote',
            field=wagtail.fields.RichTextField(blank=True, help_text='quote for the background image'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_fr',
            field=wagtail.fields.RichTextField(blank=True, help_text='quote for the background image (French)'),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_position',
            field=models.CharField(blank=True, choices=[('right', 'Right'), ('left', 'Left'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], help_text='Position of the quote', max_length=255),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 9), ('board', 18)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 1: ('wagtail.blocks.StructBlock', [[('en', 0), ('fr', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publication', 'Publication'), ('opinion', 'Opinion'), ('video', 'Video'), ('podcast', 'Podcast'), ('event', 'Event'), ('essay series', 'Essay Series'), ('media', 'Media'), ('news release', 'News Release'), ('experts', 'Experts'), ('subscribe', 'Subscribe'), ('listen', 'Listen'), ('explore', 'Explore')]}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this content item', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the title for this content item', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('type', 2), ('page', 3), ('link_override', 4), ('title_en', 5), ('title_fr', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('content', 6)]], {'required': False}), 8: ('wagtail.blocks.StreamBlock', [[('paragraph_column', 1), ('content_column', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('column', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('board', 'Board'), ('executive', 'Executive')]}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this person', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('name', 11), ('title', 11), ('title_line_2', 12), ('title_fr', 11), ('title_line_2_fr', 12), ('bio_en', 0), ('bio_fr', 0), ('page', 13), ('image_override', 14), ('link_override', 15)]], {}), 17: ('wagtail.blocks.StreamBlock', [[('member', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('board_type', 10), ('board_members', 17)]], {})}, help_text='Content of the slide'),
        ),
    ]
