# Generated by Django 5.0.6 on 2025-10-03 19:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0065_alter_annualreportslidepage_ar_slide_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 9), ('board', 19), ('auditor_report', 25)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'red-line', 'chair-name'], 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('en', 0), ('fr', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publication', 'Publication'), ('opinion', 'Opinion'), ('video', 'Video'), ('podcast', 'Podcast'), ('event', 'Event'), ('essay series', 'Essay Series'), ('media', 'Media'), ('news release', 'News Release'), ('experts', 'Experts'), ('subscribe', 'Subscribe'), ('listen', 'Listen'), ('explore', 'Explore')]}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this content item', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the title for this content item', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('type', 2), ('page', 3), ('link_override', 4), ('title_en', 5), ('title_fr', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('content', 6)]], {'required': False}), 8: ('wagtail.blocks.StreamBlock', [[('paragraph_column', 1), ('content_column', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('column', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('board', 'Board'), ('executive', 'Executive')]}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this person', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 11), ('title', 11), ('title_line_2', 12), ('title_fr', 11), ('title_line_2_fr', 12), ('bio_en', 13), ('bio_fr', 13), ('page', 14), ('image_override', 15), ('link_override', 16)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('member', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('board_type', 10), ('board_members', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'red-line'], 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('signature', 15), ('signature_text_en', 12), ('signature_text_fr', 12)]], {}), 22: ('wagtail.blocks.StreamBlock', [[('paragraph', 20), ('signature', 21)]], {}), 23: ('wagtail.blocks.StructBlock', [[('en', 22), ('fr', 22)]], {}), 24: ('wagtail.blocks.StreamBlock', [[('column', 23)]], {}), 25: ('wagtail.blocks.StructBlock', [[('title_en', 12), ('title_fr', 12), ('columns', 24)]], {})}, help_text='Content of the slide'),
        ),
    ]
