# Generated by Django 5.0.6 on 2025-10-07 19:26

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0068_alter_annualreportslidepage_ar_slide_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='ar_slide_content',
            field=wagtail.fields.StreamField([('column', 9), ('board', 19), ('auditor_report', 26), ('financial_position', 27)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'red-line', 'chair-name'], 'required': False}), 1: ('wagtail.blocks.StructBlock', [[('en', 0), ('fr', 0)]], {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('publication', 'Publication'), ('opinion', 'Opinion'), ('video', 'Video'), ('podcast', 'Podcast'), ('event', 'Event'), ('essay series', 'Essay Series'), ('media', 'Media'), ('news release', 'News Release'), ('experts', 'Experts'), ('subscribe', 'Subscribe'), ('listen', 'Listen'), ('explore', 'Explore')]}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this content item', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Override the title for this content item', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('type', 2), ('page', 3), ('link_override', 4), ('title_en', 5), ('title_fr', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('content', 6)]], {'required': False}), 8: ('wagtail.blocks.StreamBlock', [[('paragraph_column', 1), ('content_column', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('column', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('board', 'Board'), ('executive', 'Executive')]}), 11: ('wagtail.blocks.CharBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'required': False}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'help_text': 'Override the link for this person', 'required': False}), 17: ('wagtail.blocks.StructBlock', [[('name', 11), ('title', 11), ('title_line_2', 12), ('title_fr', 11), ('title_line_2_fr', 12), ('bio_en', 13), ('bio_fr', 13), ('page', 14), ('image_override', 15), ('link_override', 16)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('member', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('board_type', 10), ('board_members', 18)]], {}), 20: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h4'], 'required': False}), 21: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('signature', 15), ('signature_text', 21)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('paragraph', 20), ('signature', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('en', 23), ('fr', 23)]], {}), 25: ('wagtail.blocks.StreamBlock', [[('column', 24)]], {}), 26: ('wagtail.blocks.StructBlock', [[('title_en', 12), ('title_fr', 12), ('columns', 25)]], {}), 27: ('wagtail.blocks.StructBlock', [[('title_en', 12), ('title_fr', 12), ('cash_and_cash_equivalents', 12), ('portfolio_investments', 12), ('amounts_receivable', 12), ('prepaid_expenses', 12), ('property_and_equipment', 12), ('lease_inducement', 12), ('accounts_payable_and_accrued_liabilities', 12), ('deferred_revenue', 12), ('invested_in_capital_assets', 12), ('extrenally_restricted', 12), ('internally_restricted', 12), ('unrestricted', 12)]], {})}, help_text='Content of the slide'),
        ),
        migrations.AlterField(
            model_name='annualreportslidepage',
            name='slide_type',
            field=models.CharField(choices=[('title', 'Title'), ('toc', 'Table of Contents'), ('chairs_message', "Chair's Message"), ('presidents-message', "President's Message"), ('standard', 'Standard'), ('outputs_and_activities', 'Outputs and Activities'), ('timeline', 'Timeline'), ('financials', 'Financials')], default='standard', help_text='Type of slide', max_length=255),
        ),
    ]
