# Generated by Django 5.0.6 on 2025-10-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0073_alter_annualreportslidepage_ar_slide_content'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='download_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
