# Generated by Django 5.0.6 on 2025-11-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual_reports', '0078_alter_annualreportslidepage_ar_slide_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_font_size',
            field=models.CharField(choices=[('smaller', 'Smaller'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Font size of the quote', max_length=255),
        ),
        migrations.AddField(
            model_name='annualreportslidepage',
            name='background_quote_font_size_fr',
            field=models.CharField(choices=[('smaller', 'Smaller'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Font size of the quote (French)', max_length=255),
        ),
    ]
