# Generated by Django 5.0.6 on 2025-06-25 11:13

import django.db.models.deletion
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiai', '0002_alter_caiaihomepage_body'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAIAIAboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock())], blank=True)),
            ],
            options={
                'verbose_name': 'CAIAI About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CAIAIBioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock()), ('floated_bio', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the bio.', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image to be displayed alongside the bio.', required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text content of the bio.', required=True)), ('float_side', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')], help_text='Choose which side the image should float.'))]))], blank=True)),
            ],
            options={
                'verbose_name': 'CAIAI Bio Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
