# Generated by Django 5.0.6 on 2025-06-25 15:45

import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caiai', '0004_alter_caiaiaboutpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caiaiaboutpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock()), ('floated_bio', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title of the bio.', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image to be displayed alongside the bio.', required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], help_text='Text content of the bio.', required=True)), ('float_side', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')], help_text='Choose which side the image should float.'))])), ('caiai_objectives', wagtail.blocks.StructBlock([('objectives', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'ul', 'bold', 'italic', 'link'], help_text='Text content of the CAI AI Objectives.', required=True))]))], blank=True),
        ),
    ]
