# Generated by Django 5.0.6 on 2025-06-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caiai', '0007_alter_caiaiaboutpage_body_alter_caiaibiopage_body_and_more'),
        ('images', '0004_alter_cigionlinerendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='caiaiaboutpage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='caiaiaboutpage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caiaiaboutpage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caiaihomepage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='caiaihomepage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caiaihomepage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caiairecommendationspage',
            name='image_social',
            field=models.ForeignKey(blank=True, help_text='An image that is used when sharing on social media.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Social image'),
        ),
        migrations.AddField(
            model_name='caiairecommendationspage',
            name='social_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='caiairecommendationspage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
