# Generated by Django 3.1.1 on 2020-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogeventpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='publishing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
