# Generated by Django 5.0.6 on 2025-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_cigionlinerendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cigionlineimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
