# Generated by Django 3.1.5 on 2021-01-18 22:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeaturedmultimedia',
            name='featured_multimedia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='multimedia.multimediapage', verbose_name='Multimedia'),
        ),
        migrations.AddField(
            model_name='homepagefeaturedmultimedia',
            name='home_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_multimedia', to='home.homepage'),
        ),
    ]
