# Generated by Django 3.1.5 on 2021-01-17 18:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('home', '0002_auto_20210117_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagefeaturedexperts',
            name='featured_expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.personpage', verbose_name='Expert'),
        ),
        migrations.AddField(
            model_name='homepagefeaturedexperts',
            name='home_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_experts', to='home.homepage'),
        ),
    ]
