# Generated by Django 3.1.5 on 2021-01-27 20:47

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('home', '0004_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePromotionBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_blocks', to='home.homepage')),
                ('promotion_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='promotions.promotionblockpage', verbose_name='Promotion Block')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
