# Generated by Django 3.2.4 on 2021-12-13 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagereplacementfeaturedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagereplacementfeaturedpage',
            name='position',
            field=models.IntegerField(default=0, help_text='Enter the position of the item that will be replaced', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
            preserve_default=False,
        ),
    ]
