# Generated by Django 3.2.13 on 2022-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagereplacementfeaturedpage_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePagePromotionBlocks',
        ),
    ]
