# Generated by Django 3.2.13 on 2022-04-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0007_homepagereplacementfeaturedpage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedpage',
            name='featured_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Page'),
        ),
    ]
