# Generated by Django 3.2.15 on 2022-09-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepagereplacementfeaturedpage_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageReplacementFeaturedPage',
        ),
    ]
