# Generated by Django 5.0.6 on 2025-04-28 13:58

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_think7homepage_release_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='think7homepage',
            name='communiques',
            field=wagtail.fields.StreamField([('communique', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.T7PublicationPage'], required=False)), ('image_override', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title_override', wagtail.blocks.CharBlock(required=False))]))], blank=True),
        ),
    ]
