# Generated by Django 5.0.6 on 2025-08-28 12:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_think7homepage_communiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='think7homepage',
            name='board_members',
            field=wagtail.fields.StreamField([('board_members', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full_bio', 'Full Biography'), ('short_bio', 'Short Biography')], 'help_text': "Select the field from the person's page to populate their biography in this block. Default to 'Full Biography'.", 'max_choices': 1, 'required': False, 'verbose_name': 'Biography Source Field'}), 2: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['people.PersonPage'], 'required': True}), 3: ('wagtail.blocks.StreamBlock', [[('person', 2)]], {'required': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('bio_source_field', 1), ('persons', 3), ('cohort', 0)]], {})}),
        ),
    ]
