# Generated by Django 3.1.5 on 2021-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20210117_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='authors',
        ),
    ]
