# Generated by Django 3.1.7 on 2021-03-05 19:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_update_publication_series_field_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pdf_downloads',
            field=wagtail.fields.StreamField([('pdf_download', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(help_text='Optional text to replace the button text. If left empty, the button will read "Download PDF".', required=False)), ('display', wagtail.blocks.BooleanBlock(default=True))]))], blank=True, verbose_name='PDF Downloads'),
        ),
    ]
