# Generated by Django 3.0.7 on 2020-07-22 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('publications', '0002_create_publication_series_page_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='publication_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
