# Generated by Django 3.1.5 on 2021-01-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_publicationpage_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='editors',
        ),
    ]
