# Generated by Django 3.1.4 on 2020-12-09 02:01

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_create_chart_stream_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='authors',
            field=wagtail.core.fields.StreamField([('author', streams.blocks.AuthorBlock(page_type=['people.PersonPage'], required=True)), ('external_author', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
