# Generated by Django 3.1.4 on 2020-12-09 02:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_create_author_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='pdf_downloads',
            field=wagtail.core.fields.StreamField([('pdf_download', wagtail.core.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('button_text', wagtail.core.blocks.CharBlock(help_text='Optional text to replace the button text. If left empty, the button will read "Download PDF".', required=False))]))], blank=True, verbose_name='PDF Downloads'),
        ),
    ]
