# Generated by Django 3.1.5 on 2021-01-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publicationtypepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='publication_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.publicationtypepage'),
        ),
    ]
