# Generated by Django 3.2.4 on 2021-08-12 17:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_use_custom_image_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='ctas',
            field=wagtail.fields.StreamField([('ctas', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=False)), ('link', wagtail.blocks.CharBlock(help_text='This will only work if no file is uploaded.', required=False)), ('button_text', wagtail.blocks.ChoiceBlock(choices=[('Download', 'Download'), ('Download PDF', 'Download PDF'), ('Explore Series', 'Explore Series')], max_length=32, required=False)), ('button_icon', wagtail.blocks.ChoiceBlock(choices=[('', 'No Icon'), ('fas fa-download', 'Download'), ('fas fa-mouse-pointer', 'Pointer')], max_length=32, required=False))]))], blank=True, verbose_name='Call to Action Buttons'),
        ),
    ]
