# Generated by Django 3.1.7 on 2021-02-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_publicationpage_publicationseriespage_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlistpagefeaturedpublication',
            name='publication_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publications.publicationpage', verbose_name='Publication'),
        ),
    ]
