# Generated by Django 3.2.4 on 2022-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_add_feature_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='publicationseriespage',
            name='feature_subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
