# Generated by Django 3.1.4 on 2020-12-11 01:42

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_create_recommended_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='from_the_archives',
            field=models.BooleanField(default=False, help_text='When enabled, show the "From the Archives" label if content is featured on front page.', verbose_name='From the Archives'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='from_the_archives_blurb',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Block displayed on page.', verbose_name='From the Archives Blurb'),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='publication_type',
            field=models.CharField(choices=[('books', 'Books'), ('cigi_commentaries', 'CIGI Commentaries'), ('cigi_papers', 'CIGI Papers'), ('collected_series', 'Collected Series'), ('conference_reports', 'Conference Reports'), ('essay_series', 'Essay Series'), ('policy_briefs', 'Policy Briefs'), ('policy_memos', 'Policy Memos'), ('special_reports', 'Special Reports'), ('speeches', 'Speeches'), ('student_essay', 'Student Essay')], default='cigi_papers', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
