# Generated by Django 4.0 on 2023-01-09 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_cigionlineimage_file_hash'),
        ('publications', '0013_auto_20221214_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='image_hero',
            field=models.ForeignKey(blank=True, help_text='A landscape image that will be used on some card formats.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Hero image'),
        ),
    ]
