# Generated by Django 4.0 on 2023-07-10 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('publications', '0014_alter_publicationpage_image_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='book_epub_download',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='eBook Download'),
        ),
    ]
