# Generated by Django 3.1.5 on 2021-01-08 15:14

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_update_book_purchase_links_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='editors',
            field=wagtail.core.fields.StreamField([('editor', streams.blocks.EditorBlock(page_type=['people.PersonPage'], required=True)), ('external_editor', wagtail.core.blocks.CharBlock(required=True))], blank=True),
        ),
    ]
