# Generated by Django 4.0 on 2023-07-21 19:48

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_publicationpage_book_epub_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='book_epub_download',
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='book_epub_downloads',
            field=wagtail.fields.StreamField([('epub_download', wagtail.blocks.StructBlock([('file', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('button_text', wagtail.blocks.CharBlock(help_text='Optional text to replace the button text. If left empty, the button will read "Download Book".', required=False)), ('display', wagtail.blocks.BooleanBlock(default=True))]))], blank=True, use_json_field=True, verbose_name='ePub Downloads'),
        ),
    ]
