# Generated by Django 3.1.5 on 2021-01-07 21:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20210107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationpage',
            name='book_purchase_links',
            field=wagtail.core.fields.StreamField([('purchase_link', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))]))], blank=True),
        ),
    ]
