# Generated by Django 3.2.18 on 2024-07-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20240709_1057'),
        ('publications', '0023_auto_20240709_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme'),
        ),
    ]
