# Generated by Django 5.0.6 on 2024-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0024_publicationpage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='dph_term',
            field=models.CharField(blank=True, help_text='Override field for DPH Working Paper term. Ex. "Summer 2024"', max_length=255, verbose_name='DPH Working Paper Term'),
        ),
    ]
