# Generated by Django 5.0.6 on 2025-03-18 18:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_cigionlinerendition_file'),
        ('publications', '0027_alter_publicationpage_body'),
        ('research', '0050_projectpage_additional_members'),
        ('wagtailcore', '0093_uploadedfile'),
        ('wagtaildocs', '0013_delete_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='T7PublicationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('abstract', wagtail.fields.RichTextField()),
                ('publishing_date', models.DateTimeField(null=True)),
                ('publication_type', models.CharField(choices=[('policy_briefs', 'Policy Briefs'), ('communique', 'Communiqué')], max_length=64)),
                ('archive', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, help_text='Whether this publication was from a previous G7 summit.')),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('special_focus_authors', models.CharField(blank=True, max_length=255)),
                ('image_feature', models.ForeignKey(blank=True, help_text='A landscape image used in featuring the publication on the landing page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Feature image')),
                ('image_poster', models.ForeignKey(blank=True, help_text='A portrait image displayed on the publication page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Poster image')),
                ('pdf_attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('taskforce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='research.projectpage')),
            ],
            options={
                'verbose_name': 'T7 Publication',
                'verbose_name_plural': 'T7 Publications',
            },
            bases=('wagtailcore.page',),
        ),
    ]
