# Generated by Django 5.0.6 on 2025-03-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0028_t7publicationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='t7publicationpage',
            name='co_authors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='t7publicationpage',
            name='team_fao_italy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='t7publicationpage',
            name='united_states',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
