# Generated by Django 5.0.6 on 2025-04-28 18:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0030_t7publicationpage_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t7publicationpage',
            name='abstract',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
