# Generated by Django 5.0.6 on 2025-04-29 13:36

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0033_t7publicationpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlistpage',
            name='t7_communiques',
            field=wagtail.fields.StreamField([('t7_communique', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.T7PublicationPage'], required=False)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=False)), ('image_override', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title_override', wagtail.blocks.CharBlock(required=False))]))], blank=True, null=True),
        ),
    ]
