# Generated by Django 5.0.6 on 2025-04-29 17:09

import streams.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0035_t7publicationpage_pdf_attachment_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t7publicationpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', streams.blocks.ParagraphBlock())], blank=True, null=True),
        ),
    ]
