# Generated by Django 3.1.5 on 2021-01-17 18:14

from django.db import migrations


def populate_project_types(apps, schema_editor):
    DEFAULT_TYPES = [
        (821, 'Activity'),
        (849, 'Collaborative Research Award Project'),
        (819, 'Project'),
        (896, 'Related Project'),
        (820, 'Working Group'),
    ]
    ProjectType = apps.get_model('research', 'ProjectType')
    for drupal_id, project_type_name in DEFAULT_TYPES:
        project_type = ProjectType(name=project_type_name, drupal_taxonomy_id=drupal_id)
        project_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_project_types),
    ]
