# Generated by Django 3.0.6 on 2020-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_topicpage_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='drupal_taxonomy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
