# Generated by Django 3.1.7 on 2021-02-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_add_hero_stream_blocks'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='topicpage',
            index=models.Index(fields=['archive'], name='research_to_archive_bd91af_idx'),
        ),
    ]
