# Generated by Django 3.1.7 on 2021-03-25 01:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_update_table_stream_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicpage',
            name='submenu',
            field=wagtail.core.fields.StreamField([('menu_item', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('url', wagtail.core.blocks.URLBlock(required=True))]))], blank=True, help_text='Submenu item displayed in the hero section.'),
        ),
    ]
