# Generated by Django 3.1.1 on 2020-09-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_add_new_body_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='publishing_date',
            field=models.DateField(null=True),
        ),
    ]
