# Generated by Django 3.1.7 on 2021-05-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_use_custom_image_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlistpage',
            options={'verbose_name': 'Activity List Page'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
