# Generated by Django 3.2.4 on 2021-10-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('research', '0011_add_submenu_to_topicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='image_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Banner Image'),
        ),
    ]
