# Generated by Django 4.0 on 2023-01-09 16:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_auto_20221214_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchlandingpage',
            name='featured_publications',
            field=wagtail.fields.StreamField([('publication', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage'], required=True))], blank=True, use_json_field=True),
        ),
    ]
