# Generated by Django 3.2.18 on 2023-05-09 13:38

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='survey_findings',
            field=wagtail.fields.StreamField([('country', wagtail.blocks.StructBlock([('country', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('file', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, use_json_field=True),
        ),
    ]
