# Generated by Django 3.2.18 on 2023-05-09 17:57

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_projectpage_survey_findings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='survey_findings',
            field=wagtail.fields.StreamField([('country', wagtail.blocks.StructBlock([('country', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('file', wagtail.documents.blocks.DocumentChooserBlock(required=True))]))], blank=True, help_text='For OGBV theme only', use_json_field=True),
        ),
    ]
