# Generated by Django 4.0 on 2023-01-09 19:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0021_alter_researchlandingpage_featured_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchlandingpage',
            name='featured_publications',
            field=wagtail.fields.StreamField([('publication', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('medium_vertical', 'Medium Vertical'), ('large', 'Large')]))]))], blank=True, use_json_field=True),
        ),
    ]
