# Generated by Django 3.2.18 on 2024-02-08 18:21

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0026_auto_20240111_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='contact',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
