# Generated by Django 3.2.18 on 2024-01-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('research', '0029_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='video_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media', verbose_name='Banner Video'),
        ),
    ]
