# Generated by Django 3.2.18 on 2024-07-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0041_auto_20240619_1412'),
        ('research', '0041_countrylistpage_countrypage_countrypagefeaturedpage'),
    ]

    operations = [
    ]
