# Generated by Django 5.0.6 on 2025-01-10 15:22

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0049_alter_projectpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='additional_members',
            field=wagtail.fields.StreamField([('additional_members', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('bio_source_field', wagtail.blocks.ChoiceBlock(choices=[('full_bio', 'Full Biography'), ('short_bio', 'Short Biography')], help_text="Select the field from the person's page to populate their biography in this block. Default to 'Full Biography'.", max_choices=1, required=False, verbose_name='Biography Source Field')), ('persons', wagtail.blocks.StreamBlock([('person', wagtail.blocks.PageChooserBlock(page_type=['people.PersonPage'], required=True))], required=True))]))], blank=True),
        ),
    ]
