# Generated by Django 5.0.6 on 2025-08-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0055_alter_countrypage_body_alter_igctimelinepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='auth0_protected',
            field=models.BooleanField(default=False, help_text='When enabled, this page requires Auth0 authentication to access.', verbose_name='Auth0 Protected'),
        ),
    ]
