# Generated by Django 5.0.6 on 2025-08-11 15:58

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auth0accessrole'),
        ('research', '0056_projectpage_auth0_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='allowed_roles',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='core.auth0accessrole'),
        ),
    ]
