# Generated by Django 5.0.6 on 2025-11-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0060_alter_countrypage_body_alter_igctimelinepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='featured_pages_format',
            field=models.CharField(choices=[('standard', 'Standard'), ('medium_only', 'Medium Only'), ('large_only', 'Large Only')], default='standard', help_text='Select how featured content is displayed on the project page. Medium Only displays medium cards in rows of three. Large Only displays a large card in a single column.', max_length=20),
        ),
    ]
