# Generated by Django 5.2 on 2026-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0062_alter_countrypage_body_alter_igctimelinepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='subscribe_page',
            field=models.URLField(blank=True, help_text='The newsletter subscription landing page for this project.', null=True),
        ),
    ]
