# Generated by Django 5.2 on 2026-05-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0063_projectpage_subscribe_page'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='subscribe_page',
            field=models.ForeignKey(blank=True, help_text='The newsletter subscription landing page for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
