# Generated by Django 3.0.4 on 2020-03-27 16:53

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personpage',
            name='board_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='education',
            field=wagtail.core.fields.StreamField([('education', wagtail.core.blocks.StructBlock([('degree', wagtail.core.blocks.CharBlock()), ('school', wagtail.core.blocks.CharBlock()), ('school_website', wagtail.core.blocks.URLBlock()), ('year', wagtail.core.blocks.IntegerBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
