# Generated by Django 3.1.5 on 2021-01-17 18:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('people', '0001_initial'),
        ('menus', '0001_initial'),
        ('core', '0003_auto_20210117_1354'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='projects',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='research.ProjectPage'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='research.TopicPage'),
        ),
        migrations.AddField(
            model_name='personlistpage',
            name='image_hero',
            field=models.ForeignKey(blank=True, help_text='A large image to be displayed prominently on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='personlistpage',
            name='submenu',
            field=models.ForeignKey(blank=True, help_text='Select a submenu to appear in the right section of the hero.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menus.menu', verbose_name='Submenu'),
        ),
    ]
