# Generated by Django 3.0.4 on 2020-03-31 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('people', '0002_auto_20200327_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='image_landscape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
