# Generated by Django 3.0.5 on 2020-04-23 20:11
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_populate-person-types'),
    ]

    operations = [
        UnaccentExtension(),
    ]
