# Generated by Django 3.0.6 on 2020-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_expand_person_list_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='drupal_node_id',
            field=models.IntegerField(null=True),
        ),
    ]
