# Generated by Django 3.0.5 on 2020-04-30 17:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('people', '0004_personpage_external_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlistpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('block_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.RichTextBlock(required=True)), ('quote_author', wagtail.core.blocks.CharBlock(required=False)), ('author_title', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='personlistpage',
            name='image_hero',
            field=models.ForeignKey(blank=True, help_text='A large image to be displayed prominently on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='personlistpage',
            name='person_list_page_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Experts'), (2, 'Staff'), (3, 'Leadership')], default=0),
        ),
    ]
