# Generated by Django 3.0.4 on 2020-05-11 12:36

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_expand_person_list_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='external_publications',
            field=wagtail.core.fields.StreamField([('external_publication', wagtail.core.blocks.StructBlock([('author', wagtail.core.blocks.CharBlock(required=True)), ('location_in_work', wagtail.core.blocks.CharBlock(required=False)), ('publisher_info', wagtail.core.blocks.CharBlock(required=False)), ('publication_type', wagtail.core.blocks.ChoiceBlock(choices=[('Generic', 'Generic'), ('Book', 'Book'), ('Book Section', 'Book Section'), ('Edited Book', 'Edited Book'), ('Electronic Article', 'Electronic Article'), ('Electronic Book', 'Electronic Book'), ('Journal Article', 'Journal Article'), ('Newspaper Article', 'Newspaper Article'), ('Report', 'Report'), ('Thesis', 'Thesis'), ('Web Page', 'Web Page')])), ('secondary_author', wagtail.core.blocks.CharBlock(required=False)), ('secondary_title', wagtail.core.blocks.CharBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=False)), ('url', wagtail.core.blocks.URLBlock(required=False)), ('url_title', wagtail.core.blocks.CharBlock(required=False)), ('year', wagtail.core.blocks.IntegerBlock(required=False))]))], blank=True),
        ),
    ]
