# Generated by Django 3.1.1 on 2020-11-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_basicpage_search_terms'),
        ('people', '0005_personpage_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.theme'),
        ),
    ]
