# Generated by Django 3.0.6 on 2020-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_personpage_drupal_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontype',
            name='drupal_taxonomy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
