# Generated by Django 3.1.7 on 2021-04-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('people', '0005_update_table_stream_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlistpage',
            name='image_hero',
            field=models.ForeignKey(blank=True, help_text='A large image to be displayed prominently on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='image_media',
            field=models.ForeignKey(blank=True, help_text="A high resolution image that is downloadable from the expert's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Media photo'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='image_square',
            field=models.ForeignKey(blank=True, help_text='For circular profile images that are used throughout the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.cigionlineimage', verbose_name='Square image'),
        ),
    ]
