# Generated by Django 3.1.1 on 2020-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_personpage_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='person_weight',
            field=models.IntegerField(default=0),
        ),
    ]
