# Generated by Django 3.0.5 on 2020-05-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('people', '0008_external_publications_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpage',
            name='image_media',
            field=models.ForeignKey(blank=True, help_text="A high resolution image that is downloadable from the expert's page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Media photo'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='image_square',
            field=models.ForeignKey(blank=True, help_text='For circular profile images that are used throughout the website.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Square image'),
        ),
    ]
