# Generated by Django 3.1.7 on 2021-03-02 18:42

from django.db import migrations


def populate_person_types(apps, schema_editor):
    ADDITIONAL_TYPES = [
        (None, 'Digital Policy Hub Fellow'),
    ]
    PersonType = apps.get_model('people', 'PersonType')
    for drupal_id, person_type_name in ADDITIONAL_TYPES:
        person_type = PersonType(name=person_type_name, drupal_taxonomy_id=drupal_id)
        person_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_alter_personlistpage_search_terms'),
    ]

    operations = [
        migrations.RunPython(populate_person_types),
    ]
