# Generated by Django 4.0 on 2023-07-31 16:05

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlistpage',
            name='layout',
            field=wagtail.fields.StreamField([('row', wagtail.blocks.StructBlock([('row', wagtail.blocks.StreamBlock([('expert_card', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['people.PersonPage'], required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium')]))]))]))]))], blank=True, use_json_field=None),
        ),
    ]
