# Generated by Django 4.0 on 2023-07-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlistpage',
            name='person_list_page_type',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Experts'), (2, 'Staff'), (3, 'Leadership'), (4, 'Senior Management'), (5, 'Board Members')], default=0),
        ),
    ]
