# Generated by Django 3.1.4 on 2020-12-22 20:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_change_tweet_block_to_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='byline',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
