# Generated by Django 3.2.18 on 2024-07-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='position_secondary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
