# Generated by Django 5.0.6 on 2024-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='position_dph',
            field=models.CharField(blank=True, help_text='Digital Policy Hub Position', max_length=255, verbose_name='DPH Position'),
        ),
    ]
