# Generated by Django 5.0.6 on 2025-08-05 16:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='dph_bio',
            field=wagtail.fields.RichTextField(blank=True, help_text='A short biography that is used on the Digital Policy Hub theme.', verbose_name='Digital Policy Hub Biography'),
        ),
    ]
