# Generated by Django 5.0.6 on 2025-10-09 15:31

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0032_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='additional_programs',
            field=wagtail.fields.StreamField([('program', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': True})}, help_text='Additional programs to list under the "Programs" section on the expert/staff page.'),
        ),
    ]
