# Generated by Django 5.0.6 on 2026-01-15 22:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0034_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='additional_authored_pages',
            field=wagtail.fields.StreamField([('page', 0)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'required': True})}, help_text='Additional pages to list in the search table'),
        ),
    ]
