# Generated by Django 5.2 on 2026-09-29 14:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_alter_personlistpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlistpage',
            name='hero_link',
            field=wagtail.fields.StreamField([('hero_link', 2), ('hero_document', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use a font-awesome icon name such as fa-envelope', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('hero_link_text', 0), ('hero_link_url', 0), ('hero_link_icon', 1)]], {}), 3: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'fa-solid', 'help_text': 'Use a font-awesome style such as fa-solid or fa-light', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('hero_link_text', 0), ('hero_link_document', 3), ('hero_link_icon_style', 4), ('hero_link_icon', 1)]], {})}, help_text='Text with link to url, email or document and optional icon that appears below the page title in the hero section.'),
        ),
    ]
