"https://{default}/":
    type: upstream
    upstream: "cigionline:http"

"https://{default}/static/":
    type: proxy
    to: "https://cigionline-static-staging.s3.amazonaws.com/static/"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
