"https://{default}/":
    type: upstream
    upstream: "cigionline:http"

"https://{default}/static/":
    type: proxy
    to: "{env:STATIC_PROXY}/static/"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
