"https://{default}/":
    type: upstream
    upstream: "cigionline:http"

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"

"https://{default}/static/":
    type: proxy
    to: "https://{STATIC_PROXY}/static/"