# Generated by Django 3.1.7 on 2021-03-02 18:41

from django.db import migrations


def populate_menus(apps, schema_editor):
    INITIAL_MENUS = [
        ('about', 'About'),
        ('careers', 'Careers'),
        ('footer', 'Footer'),
        ('events', 'Events'),
        ('experts', 'Experts'),
        ('main', 'Main'),
        ('multimedia', 'Multimedia'),
        ('opinions', 'Opinions'),
        ('publications', 'Publications'),
        ('research', 'Research'),
        ('igc', 'IGC'),
        ('gcig', 'GCIG'),
        ('topic-gender', 'Topic - Gender'),
        ('topic-india', 'Topic - India'),
        ('topic-internet-governance', 'Topic - Internet Governance'),
        ('topic-platform-governance', 'Topic - Platform Governance'),
        ('topic-refugees', 'Topic - Refugees'),
        ('topic-security', 'Topic - Security'),
    ]
    Menu = apps.get_model('menus', 'Menu')
    for slug, name in INITIAL_MENUS:
        Menu.objects.create(name=name, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_menus),
    ]
