# Generated by Django 3.0.6 on 2020-05-09 01:40

from django.db import migrations


def populate_menus(apps, schema_editor):
    INITIAL_MENUS = [
        ('about', 'About'),
        ('footer', 'Footer'),
        ('events', 'Events'),
        ('experts', 'Experts'),
        ('main', 'Main'),
        ('multimedia', 'Multimedia'),
        ('opinions', 'Opinions'),
        ('publications', 'Publications'),
        ('research', 'Research'),
    ]
    Menu = apps.get_model('menus', 'Menu')
    for slug, name in INITIAL_MENUS:
        Menu.objects.create(name=name, slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_menus),
    ]
