# Generated by Django 5.0.6 on 2026-02-23 20:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_popup', '0003_alter_policypopupgrouppage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypopupgrouppage',
            name='related_files',
            field=wagtail.fields.StreamField([('file', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {})}),
        ),
    ]
