# Generated by Django 5.0.6 on 2026-02-23 23:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_popup', '0004_policypopupgrouppage_related_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypopupgrouppage',
            name='footnotes',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
