# Generated by Django 3.2.13 on 2022-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishemailnotification',
            name='manual_publish_opt_in',
            field=models.BooleanField(default=False, help_text='When checked, receive manual publish notifications; otherwise receive only scheduled publish notifications', verbose_name='Manual Publish Opt-In'),
        ),
        migrations.AddField(
            model_name='publishemailnotification',
            name='republish_opt_in',
            field=models.BooleanField(default=False, help_text='When checked, receive re-publish notifications; otherwise receive only first-time publish notifications', verbose_name='Re-publish Opt-In'),
        ),
    ]
