# Generated by Django 3.2.13 on 2022-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20220907_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishemailnotification',
            name='manual_publish_opt_in',
        ),
        migrations.RemoveField(
            model_name='publishemailnotification',
            name='republish_opt_in',
        ),
        migrations.AddField(
            model_name='publishemailnotification',
            name='state_opt_in',
            field=models.CharField(choices=[('first_time', 'First-Time Publish'), ('republish', 'Republish'), ('both', 'Both')], default='first_time', max_length=25, verbose_name='Publish State Opt-In'),
        ),
        migrations.AddField(
            model_name='publishemailnotification',
            name='trigger_opt_in',
            field=models.CharField(choices=[('manual', 'Manual Publish'), ('scheduled', 'Scheduled Publish'), ('both', 'Both')], default='scheduled', max_length=25, verbose_name='Publish Trigger Opt-In'),
        ),
    ]
