# Generated by Django 3.2.13 on 2022-04-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureslistpage',
            options={'verbose_name': 'Feature List Page'},
        ),
        migrations.AlterModelOptions(
            name='homepagefeaturedpromotionspage',
            options={'verbose_name': 'Home Page Featured Promotions Page'},
        ),
    ]
