# Generated by Django 3.2.15 on 2022-09-30 13:50

from django.db import migrations, models
import django.db.models.deletion
import promotions.models
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('features', '0002_auto_20220428_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageFeaturedContentList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_pages', wagtail.fields.StreamField([('featured_page', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage', 'articles.ArticlePage', 'articles.ArticleSeriesPage', 'multimedia.MultimediaPage', 'multimedia.MultimediaSeriesPage', 'events.EventPage', 'research.ProjectPage', 'annual_reports.AnnualReportPage']))]))], blank=True, help_text='1: large | 2-4: medium | 5-9: small', use_json_field=None)),
            ],
            options={
                'verbose_name': 'Home Page Main Features List',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedEventsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_events', wagtail.fields.StreamField([('featured_event', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['events.EventPage']))]))], blank=True, help_text='Use this list only if you want to feature different events than those featured on the Events Landing Page.', use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedExpertsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_experts', wagtail.fields.StreamField([('featured_expert', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['people.PersonPage']))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedHighlightsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_highlights', wagtail.fields.StreamField([('featured_highlight', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage', 'articles.ArticleSeriesPage']))]))], blank=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedMultimediaList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_multimedia', wagtail.fields.StreamField([('featured_multimedia', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['multimedia.MultimediaPage']))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedPromotionsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_promotions', wagtail.fields.StreamField([('featured_promotion', wagtail.blocks.StructBlock([('block', wagtail.snippets.blocks.SnippetChooserBlock(promotions.models.PromotionBlock))]))], blank=True, use_json_field=True)),
            ],
            options={
                'verbose_name': 'Home Page Featured Promotions List',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageFeaturedPublicationsList',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('featured_publications', wagtail.fields.StreamField([('featured_publication', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage']))]))], blank=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepagefeaturedpromotionspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FeaturesPagePromotionBlocks',
        ),
        migrations.DeleteModel(
            name='HomePageFeaturedPromotionsPage',
        ),
    ]
