# Generated by Django 3.2.15 on 2022-10-03 15:37

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_separate_home_page_feature_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedeventslist',
            name='featured_events',
            field=wagtail.fields.StreamField([('featured_event', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['events.EventPage']))]))], blank=True, help_text='Use this list only if you want to feature different events than those featured on the Events Landing Page.', use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepagefeaturedhighlightslist',
            name='featured_highlights',
            field=wagtail.fields.StreamField([('featured_highlight', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage', 'articles.ArticleSeriesPage']))]))], blank=True, use_json_field=True),
        ),
    ]
