# Generated by Django 3.2.18 on 2023-09-25 16:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20221003_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedcontentlist',
            name='featured_pages',
            field=wagtail.fields.StreamField([('featured_page', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage', 'articles.ArticlePage', 'articles.ArticleSeriesPage', 'multimedia.MultimediaPage', 'multimedia.MultimediaSeriesPage', 'events.EventPage', 'research.ProjectPage', 'annual_reports.AnnualReportPage']))]))], blank=True, help_text='1: large | 2-4: medium | 5-9: small', use_json_field=True),
        ),
    ]
