# Generated by Django 5.0.6 on 2025-04-24 20:26

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_alter_homepagefeaturedcontentlist_featured_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedcontentlist',
            name='featured_pages',
            field=wagtail.fields.StreamField([('featured_page', wagtail.blocks.StructBlock([('page', wagtail.blocks.PageChooserBlock(page_type=['publications.PublicationPage', 'articles.ArticlePage', 'articles.ArticleSeriesPage', 'multimedia.MultimediaPage', 'multimedia.MultimediaSeriesPage', 'events.EventPage', 'research.ProjectPage', 'annual_reports.AnnualReportPage', 'publications.T7PublicationPage']))]))], blank=True, help_text='1: large | 2-4: medium | 5-9: small'),
        ),
    ]
