# Generated by Django 5.0.6 on 2026-01-05 20:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_alter_homepagefeaturedcontentlist_featured_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagefeaturedcontentlist',
            name='featured_pages',
            field=wagtail.fields.StreamField([('featured_page', 2)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['publications.PublicationPage', 'articles.ArticlePage', 'articles.ArticleSeriesPage', 'multimedia.MultimediaPage', 'multimedia.MultimediaSeriesPage', 'events.EventPage', 'research.ProjectPage', 'annual_reports.AnnualReportPage', 'publications.T7PublicationPage', 'annual_reports.StrategicPlanSPAPage']}), 1: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Hide the publication date on the large feature rendering.', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('hide_publication_date', 1)]], {})}, help_text='1: large | 2-4: medium | 5-9: small'),
        ),
    ]
