# Generated by Django 3.2.15 on 2022-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tweet_id', models.CharField(max_length=255, unique=True)),
                ('tweet_text', models.CharField(max_length=300)),
                ('tweet_url', models.CharField(max_length=255)),
                ('tweet_created_at', models.DateTimeField()),
                ('tweet_user_id', models.CharField(max_length=255)),
                ('tweet_user_name', models.CharField(max_length=255)),
                ('tweet_user_screen_name', models.CharField(max_length=255)),
                ('tweet_user_profile_image_url', models.CharField(max_length=255)),
                ('tweet_user_profile_image_url_https', models.CharField(max_length=255)),
                ('tweet_user_url', models.CharField(max_length=255)),
            ],
        ),
    ]
