# Generated by Django 3.2.15 on 2022-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20221215_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_user_screen_name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_replies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
