# Generated by Django 3.2.15 on 2022-12-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20221215_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
