# Generated by Django 3.2.15 on 2022-12-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_tweet_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_media_alt_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_media_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_media_preview_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
