# Generated by Django 3.2.15 on 2022-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20221215_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_user_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
