# Generated by Django 3.2.15 on 2022-12-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_tweet_tweet_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
