# Generated by Django 4.0 on 2023-01-02 16:38

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_linkedinpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='post_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='user_profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='user_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
