# Generated by Django 4.0 on 2023-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_linkedinpost_post_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinpost',
            name='post_media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
