# Generated by Django 4.0 on 2023-02-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_linkedinpost_post_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_media_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
