# Generated by Django 4.0 on 2023-03-10 02:29

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_tweet_tweet_media_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_username', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_text', wagtail.fields.RichTextField(blank=True, null=True)),
                ('post_link_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_media_url', models.CharField(blank=True, max_length=255, null=True)),
                ('post_created_at', models.DateTimeField(blank=True, null=True)),
                ('post_likes', models.IntegerField(blank=True, null=True)),
                ('post_comments', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='linkedinpost',
            name='post_link_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
